import { UnparsedObject } from "@datadog/datadog-api-client";

import { ObservabilityPipelineAzureDataExplorerDestinationAuthAzureCli } from "./ObservabilityPipelineAzureDataExplorerDestinationAuthAzureCli";
import { ObservabilityPipelineAzureDataExplorerDestinationAuthClientCertificate } from "./ObservabilityPipelineAzureDataExplorerDestinationAuthClientCertificate";
import { ObservabilityPipelineAzureDataExplorerDestinationAuthClientSecret } from "./ObservabilityPipelineAzureDataExplorerDestinationAuthClientSecret";
import { ObservabilityPipelineAzureDataExplorerDestinationAuthManagedIdentity } from "./ObservabilityPipelineAzureDataExplorerDestinationAuthManagedIdentity";
import { ObservabilityPipelineAzureDataExplorerDestinationAuthManagedIdentityClientAssertion } from "./ObservabilityPipelineAzureDataExplorerDestinationAuthManagedIdentityClientAssertion";
import { ObservabilityPipelineAzureDataExplorerDestinationAuthWorkloadIdentity } from "./ObservabilityPipelineAzureDataExplorerDestinationAuthWorkloadIdentity";

/**
 * Authentication configuration for Azure Data Explorer. The `azure_credential_kind` field selects the credential type.
 */
export type ObservabilityPipelineAzureDataExplorerDestinationAuth =
  | ObservabilityPipelineAzureDataExplorerDestinationAuthAzureCli
  | ObservabilityPipelineAzureDataExplorerDestinationAuthClientSecret
  | ObservabilityPipelineAzureDataExplorerDestinationAuthClientCertificate
  | ObservabilityPipelineAzureDataExplorerDestinationAuthManagedIdentity
  | ObservabilityPipelineAzureDataExplorerDestinationAuthManagedIdentityClientAssertion
  | ObservabilityPipelineAzureDataExplorerDestinationAuthWorkloadIdentity
  | UnparsedObject;
