/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class ApiKey {
  /**
   * Date of creation of the API key.
   */
  "created"?: string;
  /**
   * Datadog user handle that created the API key.
   */
  "createdBy"?: string;
  /**
   * API key.
   */
  "key"?: string;
  /**
   * Name of your API key.
   */
  "name"?: string;

  "unparsedObject"?: any;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: {
    [key: string]: {
      name: string;
      baseName: string;
      type: string;
      required: boolean;
      format?: string;
      enumValues?: any;
    };
  } = {
    created: {
      name: "created",
      baseName: "created",
      type: "string",
      required: false,
      format: "",
    },
    createdBy: {
      name: "createdBy",
      baseName: "created_by",
      type: "string",
      required: false,
      format: "",
    },
    key: {
      name: "key",
      baseName: "key",
      type: "string",
      required: false,
      format: "",
    },
    name: {
      name: "name",
      baseName: "name",
      type: "string",
      required: false,
      format: "",
    },
  };

  static getAttributeTypeMap() {
    return ApiKey.attributeTypeMap;
  }

  public constructor() {}
}
