/**
 * Datadog API V1 Collection
 * Collection of all Datadog Public endpoints.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@datadoghq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ApplicationKey } from './ApplicationKey';
import { HttpFile } from '../http/http';

/**
* An application key response.
*/
export class ApplicationKeyResponse {
    'applicationKey'?: ApplicationKey;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "applicationKey",
            "baseName": "application_key",
            "type": "ApplicationKey",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ApplicationKeyResponse.attributeTypeMap;
    }
    
    public constructor() {
    }
}

