/**
 * Datadog API V1 Collection
 * Collection of all Datadog Public endpoints.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@datadoghq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DowntimeRecurrence } from './DowntimeRecurrence';
import { HttpFile } from '../http/http';

/**
* Downtiming gives you greater control over monitor notifications by allowing you to globally exclude scopes from alerting. Downtime settings, which can be scheduled with start and end times, prevent all alerting related to specified Datadog tags.
*/
export class Downtime {
    /**
    * If a scheduled downtime currently exists.
    */
    'active'?: boolean;
    /**
    * If a scheduled downtime is canceled.
    */
    'canceled'?: number;
    /**
    * User ID of the downtime creator.
    */
    'creatorId'?: number;
    /**
    * If a downtime has been disabled.
    */
    'disabled'?: boolean;
    /**
    * `0` for a downtime applied on `*` or all, `1` when the downtime is only scoped to hosts, or `2` when the downtime is scoped to anything but hosts.
    */
    'downtimeType'?: number;
    /**
    * POSIX timestamp to end the downtime. If not provided, the downtime is in effect indefinitely until you cancel it.
    */
    'end'?: number;
    /**
    * The downtime ID.
    */
    'id'?: number;
    /**
    * A message to include with notifications for this downtime. Email notifications can be sent to specific users by using the same `@username` notation as events.
    */
    'message'?: string;
    /**
    * A single monitor to which the downtime applies. If not provided, the downtime applies to all monitors.
    */
    'monitorId'?: number;
    /**
    * A comma-separated list of monitor tags. For example, tags that are applied directly to monitors, not tags that are used in monitor queries (which are filtered by the scope parameter), to which the downtime applies. The resulting downtime applies to monitors that match ALL provided monitor tags. For example, `service:postgres` **AND** `team:frontend`.
    */
    'monitorTags'?: Array<string>;
    /**
    * ID of the parent Downtime.
    */
    'parentId'?: number;
    'recurrence'?: DowntimeRecurrence;
    /**
    * The scope(s) to which the downtime applies. For example, `host:app2`. Provide multiple scopes as a comma-separated list like `env:dev,env:prod`. The resulting downtime applies to sources that matches ALL provided scopes (`env:dev` **AND** `env:prod`).
    */
    'scope'?: Array<string>;
    /**
    * POSIX timestamp to start the downtime. If not provided, the downtime starts the moment it is created.
    */
    'start'?: number;
    /**
    * The timezone in which to display the downtime's start and end times in Datadog applications.
    */
    'timezone'?: string;
    /**
    * ID of the last user that updated the downtime.
    */
    'updaterId'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "active",
            "baseName": "active",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "canceled",
            "baseName": "canceled",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "creatorId",
            "baseName": "creator_id",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "disabled",
            "baseName": "disabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "downtimeType",
            "baseName": "downtime_type",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "end",
            "baseName": "end",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "monitorId",
            "baseName": "monitor_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "monitorTags",
            "baseName": "monitor_tags",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "parentId",
            "baseName": "parent_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "recurrence",
            "baseName": "recurrence",
            "type": "DowntimeRecurrence",
            "format": ""
        },
        {
            "name": "scope",
            "baseName": "scope",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "start",
            "baseName": "start",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "timezone",
            "baseName": "timezone",
            "type": "string",
            "format": ""
        },
        {
            "name": "updaterId",
            "baseName": "updater_id",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return Downtime.attributeTypeMap;
    }
    
    public constructor() {
    }
}

