/**
 * Datadog API V1 Collection
 * Collection of all Datadog Public endpoints.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@datadoghq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* The aggregation methods available for metrics queries.
*/
export type FormulaAndFunctionMetricAggregation = "avg" | "min" | "max" | "sum" | "last" | "area" | "l2norm" ;
