/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FormulaAndFunctionMetricAggregation } from "./FormulaAndFunctionMetricAggregation";
import { FormulaAndFunctionProcessQueryDataSource } from "./FormulaAndFunctionProcessQueryDataSource";
import { QuerySortOrder } from "./QuerySortOrder";

export class FormulaAndFunctionProcessQueryDefinition {
  "aggregator"?: FormulaAndFunctionMetricAggregation;
  "dataSource": FormulaAndFunctionProcessQueryDataSource;
  /**
   * Whether to normalize the CPU percentages.
   */
  "isNormalizedCpu"?: boolean;
  /**
   * Number of hits to return.
   */
  "limit"?: number;
  /**
   * Process metric name.
   */
  "metric": string;
  /**
   * Name of query for use in formulas.
   */
  "name": string;
  "sort"?: QuerySortOrder;
  /**
   * An array of tags to filter by.
   */
  "tagFilters"?: Array<string>;
  /**
   * Text to use as filter.
   */
  "textFilter"?: string;

  "unparsedObject"?: any;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: {
    [key: string]: {
      name: string;
      baseName: string;
      type: string;
      required: boolean;
      format?: string;
    };
  } = {
    aggregator: {
      name: "aggregator",
      baseName: "aggregator",
      type: "FormulaAndFunctionMetricAggregation",
      required: false,
    },
    dataSource: {
      name: "dataSource",
      baseName: "data_source",
      type: "FormulaAndFunctionProcessQueryDataSource",
      required: true,
    },
    isNormalizedCpu: {
      name: "isNormalizedCpu",
      baseName: "is_normalized_cpu",
      type: "boolean",
      required: false,
    },
    limit: {
      name: "limit",
      baseName: "limit",
      type: "number",
      required: false,
      format: "int64",
    },
    metric: {
      name: "metric",
      baseName: "metric",
      type: "string",
      required: true,
    },
    name: {
      name: "name",
      baseName: "name",
      type: "string",
      required: true,
    },
    sort: {
      name: "sort",
      baseName: "sort",
      type: "QuerySortOrder",
      required: false,
    },
    tagFilters: {
      name: "tagFilters",
      baseName: "tag_filters",
      type: "Array<string>",
      required: false,
    },
    textFilter: {
      name: "textFilter",
      baseName: "text_filter",
      type: "string",
      required: false,
    },
  };

  static getAttributeTypeMap() {
    return FormulaAndFunctionProcessQueryDefinition.attributeTypeMap;
  }

  public constructor() {}
}
