/**
 * Datadog API V1 Collection
 * Collection of all Datadog Public endpoints.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@datadoghq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LogQueryDefinition } from './LogQueryDefinition';
import { HttpFile } from '../http/http';

/**
* An updated geomap widget.
*/
export class GeomapWidgetRequest {
    'logQuery'?: LogQueryDefinition;
    /**
    * The widget metrics query.
    */
    'q'?: string;
    'rumQuery'?: LogQueryDefinition;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "logQuery",
            "baseName": "log_query",
            "type": "LogQueryDefinition",
            "format": ""
        },
        {
            "name": "q",
            "baseName": "q",
            "type": "string",
            "format": ""
        },
        {
            "name": "rumQuery",
            "baseName": "rum_query",
            "type": "LogQueryDefinition",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GeomapWidgetRequest.attributeTypeMap;
    }
    
    public constructor() {
    }
}

