/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GroupWidgetDefinitionType } from "./GroupWidgetDefinitionType";
import { Widget } from "./Widget";
import { WidgetLayoutType } from "./WidgetLayoutType";
import { WidgetTextAlign } from "./WidgetTextAlign";

export class GroupWidgetDefinition {
  /**
   * Background color of the group title.
   */
  "backgroundColor"?: string;
  /**
   * URL of image to display as a banner for the group.
   */
  "bannerImg"?: string;
  "layoutType": WidgetLayoutType;
  /**
   * Whether to show the title or not.
   */
  "showTitle"?: boolean;
  /**
   * Title of the widget.
   */
  "title"?: string;
  "titleAlign"?: WidgetTextAlign;
  "type": GroupWidgetDefinitionType;
  /**
   * List of widget groups.
   */
  "widgets": Array<Widget>;

  "unparsedObject"?: any;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: {
    [key: string]: {
      name: string;
      baseName: string;
      type: string;
      required: boolean;
      format?: string;
    };
  } = {
    backgroundColor: {
      name: "backgroundColor",
      baseName: "background_color",
      type: "string",
      required: false,
    },
    bannerImg: {
      name: "bannerImg",
      baseName: "banner_img",
      type: "string",
      required: false,
    },
    layoutType: {
      name: "layoutType",
      baseName: "layout_type",
      type: "WidgetLayoutType",
      required: true,
    },
    showTitle: {
      name: "showTitle",
      baseName: "show_title",
      type: "boolean",
      required: false,
    },
    title: {
      name: "title",
      baseName: "title",
      type: "string",
      required: false,
    },
    titleAlign: {
      name: "titleAlign",
      baseName: "title_align",
      type: "WidgetTextAlign",
      required: false,
    },
    type: {
      name: "type",
      baseName: "type",
      type: "GroupWidgetDefinitionType",
      required: true,
    },
    widgets: {
      name: "widgets",
      baseName: "widgets",
      type: "Array<Widget>",
      required: true,
    },
  };

  static getAttributeTypeMap() {
    return GroupWidgetDefinition.attributeTypeMap;
  }

  public constructor() {}
}
