/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class HostMuteSettings {
  /**
   * POSIX timestamp in seconds when the host is unmuted. If omitted, the host remains muted until explicitly unmuted.
   */
  "end"?: number;
  /**
   * Message to associate with the muting of this host.
   */
  "message"?: string;
  /**
   * If true and the host is already muted, replaces existing host mute settings.
   */
  "override"?: boolean;

  "unparsedObject"?: any;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: {
    [key: string]: {
      baseName: string;
      type: string;
      required?: boolean;
      format?: string;
    };
  } = {
    end: {
      baseName: "end",
      type: "number",

      format: "int64",
    },
    message: {
      baseName: "message",
      type: "string",
    },
    override: {
      baseName: "override",
      type: "boolean",
    },
  };

  static getAttributeTypeMap() {
    return HostMuteSettings.attributeTypeMap;
  }

  public constructor() {}
}
