/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IPPrefixesAPI } from "./IPPrefixesAPI";
import { IPPrefixesAPM } from "./IPPrefixesAPM";
import { IPPrefixesAgents } from "./IPPrefixesAgents";
import { IPPrefixesLogs } from "./IPPrefixesLogs";
import { IPPrefixesProcess } from "./IPPrefixesProcess";
import { IPPrefixesSynthetics } from "./IPPrefixesSynthetics";
import { IPPrefixesWebhooks } from "./IPPrefixesWebhooks";
import { ObjectSerializer } from "./ObjectSerializer";

/**
 * IP ranges.
 */

export class IPRanges {
  "agents"?: IPPrefixesAgents;
  "api"?: IPPrefixesAPI;
  "apm"?: IPPrefixesAPM;
  "logs"?: IPPrefixesLogs;
  /**
   * Date when last updated, in the form `YYYY-MM-DD-hh-mm-ss`.
   */
  "modified"?: string;
  "process"?: IPPrefixesProcess;
  "synthetics"?: IPPrefixesSynthetics;
  /**
   * Version of the IP list.
   */
  "version"?: number;
  "webhooks"?: IPPrefixesWebhooks;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: {
    [key: string]: { baseName: string; type: string; format: string };
  } = {
    agents: {
      baseName: "agents",
      type: "IPPrefixesAgents",
      format: "",
    },
    api: {
      baseName: "api",
      type: "IPPrefixesAPI",
      format: "",
    },
    apm: {
      baseName: "apm",
      type: "IPPrefixesAPM",
      format: "",
    },
    logs: {
      baseName: "logs",
      type: "IPPrefixesLogs",
      format: "",
    },
    modified: {
      baseName: "modified",
      type: "string",
      format: "",
    },
    process: {
      baseName: "process",
      type: "IPPrefixesProcess",
      format: "",
    },
    synthetics: {
      baseName: "synthetics",
      type: "IPPrefixesSynthetics",
      format: "",
    },
    version: {
      baseName: "version",
      type: "number",
      format: "int64",
    },
    webhooks: {
      baseName: "webhooks",
      type: "IPPrefixesWebhooks",
      format: "",
    },
  };

  static getAttributeTypeMap() {
    return IPRanges.attributeTypeMap;
  }

  static deserialize(data: { [key: string]: any }): IPRanges {
    const res = new IPRanges();

    res.agents = ObjectSerializer.deserialize(
      data.agents,
      "IPPrefixesAgents",
      ""
    );

    res.api = ObjectSerializer.deserialize(data.api, "IPPrefixesAPI", "");

    res.apm = ObjectSerializer.deserialize(data.apm, "IPPrefixesAPM", "");

    res.logs = ObjectSerializer.deserialize(data.logs, "IPPrefixesLogs", "");

    res.modified = ObjectSerializer.deserialize(data.modified, "string", "");

    res.process = ObjectSerializer.deserialize(
      data.process,
      "IPPrefixesProcess",
      ""
    );

    res.synthetics = ObjectSerializer.deserialize(
      data.synthetics,
      "IPPrefixesSynthetics",
      ""
    );

    res.version = ObjectSerializer.deserialize(data.version, "number", "int64");

    res.webhooks = ObjectSerializer.deserialize(
      data.webhooks,
      "IPPrefixesWebhooks",
      ""
    );

    return res;
  }

  static serialize(data: IPRanges): { [key: string]: any } {
    const attributeTypes = IPRanges.getAttributeTypeMap();
    const res: { [index: string]: any } = {};
    for (const [key, value] of Object.entries(data)) {
      if (!(key in attributeTypes)) {
        throw new TypeError(`${key} attribute not in schema`);
      }
    }
    res.agents = ObjectSerializer.serialize(
      data.agents,
      "IPPrefixesAgents",
      ""
    );

    res.api = ObjectSerializer.serialize(data.api, "IPPrefixesAPI", "");

    res.apm = ObjectSerializer.serialize(data.apm, "IPPrefixesAPM", "");

    res.logs = ObjectSerializer.serialize(data.logs, "IPPrefixesLogs", "");

    res.modified = ObjectSerializer.serialize(data.modified, "string", "");

    res.process = ObjectSerializer.serialize(
      data.process,
      "IPPrefixesProcess",
      ""
    );

    res.synthetics = ObjectSerializer.serialize(
      data.synthetics,
      "IPPrefixesSynthetics",
      ""
    );

    res.version = ObjectSerializer.serialize(data.version, "number", "int64");

    res.webhooks = ObjectSerializer.serialize(
      data.webhooks,
      "IPPrefixesWebhooks",
      ""
    );

    return res;
  }

  public constructor() {}
}
