/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class LogContent {
  /**
   * JSON object of attributes from your log.
   */
  "attributes"?: { [key: string]: any };
  /**
   * Name of the machine from where the logs are being sent.
   */
  "host"?: string;
  /**
   * The message [reserved attribute](https://docs.datadoghq.com/logs/log_collection/#reserved-attributes) of your log. By default, Datadog ingests the value of the message attribute as the body of the log entry. That value is then highlighted and displayed in the Logstream, where it is indexed for full text search.
   */
  "message"?: string;
  /**
   * The name of the application or service generating the log events. It is used to switch from Logs to APM, so make sure you define the same value when you use both products.
   */
  "service"?: string;
  /**
   * Array of tags associated with your log.
   */
  "tags"?: Array<any>;
  /**
   * Timestamp of your log.
   */
  "timestamp"?: Date;

  "unparsedObject"?: any;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: {
    [key: string]: {
      name: string;
      baseName: string;
      type: string;
      required: boolean;
      format?: string;
    };
  } = {
    attributes: {
      name: "attributes",
      baseName: "attributes",
      type: "{ [key: string]: any; }",
      required: false,
    },
    host: {
      name: "host",
      baseName: "host",
      type: "string",
      required: false,
    },
    message: {
      name: "message",
      baseName: "message",
      type: "string",
      required: false,
    },
    service: {
      name: "service",
      baseName: "service",
      type: "string",
      required: false,
    },
    tags: {
      name: "tags",
      baseName: "tags",
      type: "Array<any>",
      required: false,
      format: "string",
    },
    timestamp: {
      name: "timestamp",
      baseName: "timestamp",
      type: "Date",
      required: false,
      format: "date-time",
    },
  };

  static getAttributeTypeMap() {
    return LogContent.attributeTypeMap;
  }

  public constructor() {}
}
