"use strict";
/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.LogsExclusion = void 0;
var ObjectSerializer_1 = require("./ObjectSerializer");
/**
* Represents the index exclusion filter object from configuration API.
*/
var LogsExclusion = /** @class */ (function () {
    function LogsExclusion() {
    }
    LogsExclusion.getAttributeTypeMap = function () {
        return LogsExclusion.attributeTypeMap;
    };
    LogsExclusion.deserialize = function (data) {
        var res = new LogsExclusion();
        res.filter = ObjectSerializer_1.ObjectSerializer.deserialize(data.filter, "LogsExclusionFilter", "");
        res.isEnabled = ObjectSerializer_1.ObjectSerializer.deserialize(data.is_enabled, "boolean", "");
        if (data.name === undefined) {
            throw new TypeError("missing required attribute 'name' on 'LogsExclusion' object");
        }
        res.name = ObjectSerializer_1.ObjectSerializer.deserialize(data.name, "string", "");
        return res;
    };
    LogsExclusion.serialize = function (data) {
        var attributeTypes = LogsExclusion.getAttributeTypeMap();
        var res = {};
        for (var _i = 0, _a = Object.entries(data); _i < _a.length; _i++) {
            var _b = _a[_i], key = _b[0], value = _b[1];
            if (!(key in attributeTypes)) {
                throw new TypeError(key + " attribute not in schema");
            }
        }
        res.filter = ObjectSerializer_1.ObjectSerializer.serialize(data.filter, "LogsExclusionFilter", "");
        res.is_enabled = ObjectSerializer_1.ObjectSerializer.serialize(data.isEnabled, "boolean", "");
        if (data.name === undefined) {
            throw new TypeError("missing required attribute 'name' on 'LogsExclusion' object");
        }
        res.name = ObjectSerializer_1.ObjectSerializer.serialize(data.name, "string", "");
        return res;
    };
    LogsExclusion.discriminator = undefined;
    LogsExclusion.attributeTypeMap = {
        "filter": {
            "baseName": "filter",
            "type": "LogsExclusionFilter",
            "format": ""
        },
        "isEnabled": {
            "baseName": "is_enabled",
            "type": "boolean",
            "format": ""
        },
        "name": {
            "baseName": "name",
            "type": "string",
            "format": ""
        }
    };
    return LogsExclusion;
}());
exports.LogsExclusion = LogsExclusion;
//# sourceMappingURL=LogsExclusion.js.map