/**
 * Datadog API V1 Collection
 * Collection of all Datadog Public endpoints.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@datadoghq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Define computation for a log query.
*/
export class LogsQueryCompute {
    /**
    * The aggregation method.
    */
    'aggregation': string;
    /**
    * Facet name.
    */
    'facet'?: string;
    /**
    * Define a time interval in seconds.
    */
    'interval'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "aggregation",
            "baseName": "aggregation",
            "type": "string",
            "format": ""
        },
        {
            "name": "facet",
            "baseName": "facet",
            "type": "string",
            "format": ""
        },
        {
            "name": "interval",
            "baseName": "interval",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return LogsQueryCompute.attributeTypeMap;
    }
    
    public constructor() {
    }
}

