"use strict";
/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.LogsIndex = void 0;
var ObjectSerializer_1 = require("./ObjectSerializer");
/**
* Object describing a Datadog Log index.
*/
var LogsIndex = /** @class */ (function () {
    function LogsIndex() {
    }
    LogsIndex.getAttributeTypeMap = function () {
        return LogsIndex.attributeTypeMap;
    };
    LogsIndex.deserialize = function (data) {
        var res = new LogsIndex();
        res.dailyLimit = ObjectSerializer_1.ObjectSerializer.deserialize(data.daily_limit, "number", "int64");
        res.exclusionFilters = ObjectSerializer_1.ObjectSerializer.deserialize(data.exclusion_filters, "Array<LogsExclusion>", "");
        if (data.filter === undefined) {
            throw new TypeError("missing required attribute 'filter' on 'LogsIndex' object");
        }
        res.filter = ObjectSerializer_1.ObjectSerializer.deserialize(data.filter, "LogsFilter", "");
        res.isRateLimited = ObjectSerializer_1.ObjectSerializer.deserialize(data.is_rate_limited, "boolean", "");
        if (data.name === undefined) {
            throw new TypeError("missing required attribute 'name' on 'LogsIndex' object");
        }
        res.name = ObjectSerializer_1.ObjectSerializer.deserialize(data.name, "string", "");
        res.numRetentionDays = ObjectSerializer_1.ObjectSerializer.deserialize(data.num_retention_days, "number", "int64");
        return res;
    };
    LogsIndex.serialize = function (data) {
        var attributeTypes = LogsIndex.getAttributeTypeMap();
        var res = {};
        for (var _i = 0, _a = Object.entries(data); _i < _a.length; _i++) {
            var _b = _a[_i], key = _b[0], value = _b[1];
            if (!(key in attributeTypes)) {
                throw new TypeError(key + " attribute not in schema");
            }
        }
        res.daily_limit = ObjectSerializer_1.ObjectSerializer.serialize(data.dailyLimit, "number", "int64");
        res.exclusion_filters = ObjectSerializer_1.ObjectSerializer.serialize(data.exclusionFilters, "Array<LogsExclusion>", "");
        if (data.filter === undefined) {
            throw new TypeError("missing required attribute 'filter' on 'LogsIndex' object");
        }
        res.filter = ObjectSerializer_1.ObjectSerializer.serialize(data.filter, "LogsFilter", "");
        res.is_rate_limited = ObjectSerializer_1.ObjectSerializer.serialize(data.isRateLimited, "boolean", "");
        if (data.name === undefined) {
            throw new TypeError("missing required attribute 'name' on 'LogsIndex' object");
        }
        res.name = ObjectSerializer_1.ObjectSerializer.serialize(data.name, "string", "");
        res.num_retention_days = ObjectSerializer_1.ObjectSerializer.serialize(data.numRetentionDays, "number", "int64");
        return res;
    };
    LogsIndex.discriminator = undefined;
    LogsIndex.attributeTypeMap = {
        "dailyLimit": {
            "baseName": "daily_limit",
            "type": "number",
            "format": "int64"
        },
        "exclusionFilters": {
            "baseName": "exclusion_filters",
            "type": "Array<LogsExclusion>",
            "format": ""
        },
        "filter": {
            "baseName": "filter",
            "type": "LogsFilter",
            "format": ""
        },
        "isRateLimited": {
            "baseName": "is_rate_limited",
            "type": "boolean",
            "format": ""
        },
        "name": {
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        "numRetentionDays": {
            "baseName": "num_retention_days",
            "type": "number",
            "format": "int64"
        }
    };
    return LogsIndex;
}());
exports.LogsIndex = LogsIndex;
//# sourceMappingURL=LogsIndex.js.map