"use strict";
/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MetricSearchResponse = void 0;
var ObjectSerializer_1 = require("./ObjectSerializer");
/**
* Object containing the list of metrics matching the search query.
*/
var MetricSearchResponse = /** @class */ (function () {
    function MetricSearchResponse() {
    }
    MetricSearchResponse.getAttributeTypeMap = function () {
        return MetricSearchResponse.attributeTypeMap;
    };
    MetricSearchResponse.deserialize = function (data) {
        var res = new MetricSearchResponse();
        res.results = ObjectSerializer_1.ObjectSerializer.deserialize(data.results, "MetricSearchResponseResults", "");
        return res;
    };
    MetricSearchResponse.serialize = function (data) {
        var attributeTypes = MetricSearchResponse.getAttributeTypeMap();
        var res = {};
        for (var _i = 0, _a = Object.entries(data); _i < _a.length; _i++) {
            var _b = _a[_i], key = _b[0], value = _b[1];
            if (!(key in attributeTypes)) {
                throw new TypeError(key + " attribute not in schema");
            }
        }
        res.results = ObjectSerializer_1.ObjectSerializer.serialize(data.results, "MetricSearchResponseResults", "");
        return res;
    };
    MetricSearchResponse.discriminator = undefined;
    MetricSearchResponse.attributeTypeMap = {
        "results": {
            "baseName": "results",
            "type": "MetricSearchResponseResults",
            "format": ""
        }
    };
    return MetricSearchResponse;
}());
exports.MetricSearchResponse = MetricSearchResponse;
//# sourceMappingURL=MetricSearchResponse.js.map