/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MonitorStateGroup } from "./MonitorStateGroup";
import { ObjectSerializer } from "./ObjectSerializer";

/**
 * Wrapper object with the different monitor states.
 */

export class MonitorState {
  /**
   * Dictionary where the keys are groups (comma separated lists of tags) and the values are the list of groups your monitor is broken down on.
   */
  "groups"?: { [key: string]: MonitorStateGroup };

  "unparsedObject"?: any;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: {
    [key: string]: { baseName: string; type: string; format: string };
  } = {
    groups: {
      baseName: "groups",
      type: "{ [key: string]: MonitorStateGroup; }",
      format: "",
    },
  };

  static getAttributeTypeMap() {
    return MonitorState.attributeTypeMap;
  }

  static deserialize(data: { [key: string]: any }): MonitorState {
    const res = new MonitorState();

    res.groups = ObjectSerializer.deserialize(
      data.groups,
      "{ [key: string]: MonitorStateGroup; }",
      ""
    );

    return res;
  }

  static serialize(data: MonitorState): { [key: string]: any } {
    const attributeTypes = MonitorState.getAttributeTypeMap();
    const res: { [index: string]: any } = {};
    for (const [key, value] of Object.entries(data)) {
      if (!(key in attributeTypes)) {
        throw new TypeError(`${key} attribute not in schema`);
      }
    }
    if (data?.unparsedObject !== undefined) {
      return data.unparsedObject;
    }
    res.groups = ObjectSerializer.serialize(
      data.groups,
      "{ [key: string]: MonitorStateGroup; }",
      ""
    );

    return res;
  }

  public constructor() {}
}
