/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HeatMapWidgetDefinition } from "./HeatMapWidgetDefinition";
import { NotebookCellTime } from "./NotebookCellTime";
import { NotebookGraphSize } from "./NotebookGraphSize";
import { NotebookSplitBy } from "./NotebookSplitBy";

export class NotebookHeatMapCellAttributes {
  "definition": HeatMapWidgetDefinition;
  "graphSize"?: NotebookGraphSize;
  "splitBy"?: NotebookSplitBy;
  "time"?: NotebookCellTime;

  "unparsedObject"?: any;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: {
    [key: string]: {
      name: string;
      baseName: string;
      type: string;
      required: boolean;
      format?: string;
    };
  } = {
    definition: {
      name: "definition",
      baseName: "definition",
      type: "HeatMapWidgetDefinition",
      required: true,
    },
    graphSize: {
      name: "graphSize",
      baseName: "graph_size",
      type: "NotebookGraphSize",
      required: false,
    },
    splitBy: {
      name: "splitBy",
      baseName: "split_by",
      type: "NotebookSplitBy",
      required: false,
    },
    time: {
      name: "time",
      baseName: "time",
      type: "NotebookCellTime",
      required: false,
    },
  };

  static getAttributeTypeMap() {
    return NotebookHeatMapCellAttributes.attributeTypeMap;
  }

  public constructor() {}
}
