/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class NotebookAbsoluteTime {
  /**
   * The end time.
   */
  "end": Date;
  /**
   * Indicates whether the timeframe should be shifted to end at the current time.
   */
  "live"?: boolean;
  /**
   * The start time.
   */
  "start": Date;

  "unparsedObject"?: any;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: {
    [key: string]: {
      baseName: string;
      type: string;
      required?: boolean;
      format?: string;
    };
  } = {
    end: {
      baseName: "end",
      type: "Date",
      required: true,
      format: "date-time",
    },
    live: {
      baseName: "live",
      type: "boolean",
    },
    start: {
      baseName: "start",
      type: "Date",
      required: true,
      format: "date-time",
    },
  };

  static getAttributeTypeMap() {
    return NotebookAbsoluteTime.attributeTypeMap;
  }

  public constructor() {}
}
