"use strict";
/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.OrganizationSettingsSamlAutocreateUsersDomains = void 0;
var ObjectSerializer_1 = require("./ObjectSerializer");
/**
* Has two properties, `enabled` (boolean) and `domains`, which is a list of domains without the @ symbol.
*/
var OrganizationSettingsSamlAutocreateUsersDomains = /** @class */ (function () {
    function OrganizationSettingsSamlAutocreateUsersDomains() {
    }
    OrganizationSettingsSamlAutocreateUsersDomains.getAttributeTypeMap = function () {
        return OrganizationSettingsSamlAutocreateUsersDomains.attributeTypeMap;
    };
    OrganizationSettingsSamlAutocreateUsersDomains.deserialize = function (data) {
        var res = new OrganizationSettingsSamlAutocreateUsersDomains();
        res.domains = ObjectSerializer_1.ObjectSerializer.deserialize(data.domains, "Array<string>", "");
        res.enabled = ObjectSerializer_1.ObjectSerializer.deserialize(data.enabled, "boolean", "");
        return res;
    };
    OrganizationSettingsSamlAutocreateUsersDomains.serialize = function (data) {
        var attributeTypes = OrganizationSettingsSamlAutocreateUsersDomains.getAttributeTypeMap();
        var res = {};
        for (var _i = 0, _a = Object.entries(data); _i < _a.length; _i++) {
            var _b = _a[_i], key = _b[0], value = _b[1];
            if (!(key in attributeTypes)) {
                throw new TypeError(key + " attribute not in schema");
            }
        }
        res.domains = ObjectSerializer_1.ObjectSerializer.serialize(data.domains, "Array<string>", "");
        res.enabled = ObjectSerializer_1.ObjectSerializer.serialize(data.enabled, "boolean", "");
        return res;
    };
    OrganizationSettingsSamlAutocreateUsersDomains.discriminator = undefined;
    OrganizationSettingsSamlAutocreateUsersDomains.attributeTypeMap = {
        "domains": {
            "baseName": "domains",
            "type": "Array<string>",
            "format": ""
        },
        "enabled": {
            "baseName": "enabled",
            "type": "boolean",
            "format": ""
        }
    };
    return OrganizationSettingsSamlAutocreateUsersDomains;
}());
exports.OrganizationSettingsSamlAutocreateUsersDomains = OrganizationSettingsSamlAutocreateUsersDomains;
//# sourceMappingURL=OrganizationSettingsSamlAutocreateUsersDomains.js.map