/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class ProcessQueryDefinition {
  /**
   * List of processes.
   */
  "filterBy"?: Array<string>;
  /**
   * Max number of items in the filter list.
   */
  "limit"?: number;
  /**
   * Your chosen metric.
   */
  "metric": string;
  /**
   * Your chosen search term.
   */
  "searchBy"?: string;

  "unparsedObject"?: any;

  static readonly attributeTypeMap: {
    [key: string]: {
      baseName: string;
      type: string;
      required?: boolean;
      format?: string;
    };
  } = {
    filterBy: {
      baseName: "filter_by",
      type: "Array<string>",
    },
    limit: {
      baseName: "limit",
      type: "number",

      format: "int64",
    },
    metric: {
      baseName: "metric",
      type: "string",
      required: true,
    },
    searchBy: {
      baseName: "search_by",
      type: "string",
    },
  };

  static getAttributeTypeMap() {
    return ProcessQueryDefinition.attributeTypeMap;
  }

  public constructor() {}
}
