/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QueryValueWidgetDefinitionType } from './QueryValueWidgetDefinitionType';
import { QueryValueWidgetRequest } from './QueryValueWidgetRequest';
import { WidgetCustomLink } from './WidgetCustomLink';
import { WidgetTextAlign } from './WidgetTextAlign';
import { WidgetTime } from './WidgetTime';
/**
* Query values display the current value of a given metric, APM, or log query.
*/
export declare class QueryValueWidgetDefinition {
    /**
    * Whether to use auto-scaling or not.
    */
    'autoscale'?: boolean;
    /**
    * List of custom links.
    */
    'customLinks'?: Array<WidgetCustomLink>;
    /**
    * Display a unit of your choice on the widget.
    */
    'customUnit'?: string;
    /**
    * Number of decimals to show. If not defined, the widget uses the raw value.
    */
    'precision'?: number;
    /**
    * Widget definition.
    */
    'requests': Array<QueryValueWidgetRequest>;
    'textAlign'?: WidgetTextAlign;
    'time'?: WidgetTime;
    /**
    * Title of your widget.
    */
    'title'?: string;
    'titleAlign'?: WidgetTextAlign;
    /**
    * Size of the title.
    */
    'titleSize'?: string;
    'type': QueryValueWidgetDefinitionType;
    static readonly discriminator: string | undefined;
    static readonly attributeTypeMap: {
        [key: string]: {
            baseName: string;
            type: string;
            format: string;
        };
    };
    static getAttributeTypeMap(): {
        [key: string]: {
            baseName: string;
            type: string;
            format: string;
        };
    };
    static deserialize(data: {
        [key: string]: any;
    }): QueryValueWidgetDefinition;
    static serialize(data: QueryValueWidgetDefinition): {
        [key: string]: any;
    };
    constructor();
}
