/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ResponseMetaAttributes } from "./ResponseMetaAttributes";
import { SLOCorrection } from "./SLOCorrection";
import { ObjectSerializer } from "./ObjectSerializer";

/**
 * A list of  SLO correction objects.
 */

export class SLOCorrectionListResponse {
  /**
   * The list of of SLO corrections objects.
   */
  "data"?: Array<SLOCorrection>;
  "meta"?: ResponseMetaAttributes;

  "unparsedObject"?: any;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: {
    [key: string]: { baseName: string; type: string; format: string };
  } = {
    data: {
      baseName: "data",
      type: "Array<SLOCorrection>",
      format: "",
    },
    meta: {
      baseName: "meta",
      type: "ResponseMetaAttributes",
      format: "",
    },
  };

  static getAttributeTypeMap() {
    return SLOCorrectionListResponse.attributeTypeMap;
  }

  static deserialize(data: { [key: string]: any }): SLOCorrectionListResponse {
    const res = new SLOCorrectionListResponse();

    res.data = ObjectSerializer.deserialize(
      data.data,
      "Array<SLOCorrection>",
      ""
    );

    res.meta = ObjectSerializer.deserialize(
      data.meta,
      "ResponseMetaAttributes",
      ""
    );

    return res;
  }

  static serialize(data: SLOCorrectionListResponse): { [key: string]: any } {
    const attributeTypes = SLOCorrectionListResponse.getAttributeTypeMap();
    const res: { [index: string]: any } = {};
    for (const [key, value] of Object.entries(data)) {
      if (!(key in attributeTypes)) {
        throw new TypeError(`${key} attribute not in schema`);
      }
    }
    if (data?.unparsedObject !== undefined) {
      return data.unparsedObject;
    }
    res.data = ObjectSerializer.serialize(
      data.data,
      "Array<SLOCorrection>",
      ""
    );

    res.meta = ObjectSerializer.serialize(
      data.meta,
      "ResponseMetaAttributes",
      ""
    );

    return res;
  }

  public constructor() {}
}
