/**
 * Datadog API V1 Collection
 * Collection of all Datadog Public endpoints.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@datadoghq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* An Object of metric units.
*/
export class SLOHistoryMetricsSeriesMetadataUnit {
    /**
    * The family of metric unit, for example `bytes` is the family for `kibibyte`, `byte`, and `bit` units.
    */
    'family'?: string;
    /**
    * The ID of the metric unit.
    */
    'id'?: number;
    /**
    * The unit of the metric, for instance `byte`.
    */
    'name'?: string;
    /**
    * The plural Unit of metric, for instance `bytes`.
    */
    'plural'?: string;
    /**
    * The scale factor of metric unit, for instance `1.0`.
    */
    'scaleFactor'?: number;
    /**
    * A shorter and abbreviated version of the metric unit, for instance `B`.
    */
    'shortName'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "family",
            "baseName": "family",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "plural",
            "baseName": "plural",
            "type": "string",
            "format": ""
        },
        {
            "name": "scaleFactor",
            "baseName": "scale_factor",
            "type": "number",
            "format": "double"
        },
        {
            "name": "shortName",
            "baseName": "short_name",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SLOHistoryMetricsSeriesMetadataUnit.attributeTypeMap;
    }
    
    public constructor() {
    }
}

