"use strict";
/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SLOListResponseMetadata = void 0;
var ObjectSerializer_1 = require("./ObjectSerializer");
/**
* The metadata object containing additional information about the list of SLOs.
*/
var SLOListResponseMetadata = /** @class */ (function () {
    function SLOListResponseMetadata() {
    }
    SLOListResponseMetadata.getAttributeTypeMap = function () {
        return SLOListResponseMetadata.attributeTypeMap;
    };
    SLOListResponseMetadata.deserialize = function (data) {
        var res = new SLOListResponseMetadata();
        res.page = ObjectSerializer_1.ObjectSerializer.deserialize(data.page, "SLOListResponseMetadataPage", "");
        return res;
    };
    SLOListResponseMetadata.serialize = function (data) {
        var attributeTypes = SLOListResponseMetadata.getAttributeTypeMap();
        var res = {};
        for (var _i = 0, _a = Object.entries(data); _i < _a.length; _i++) {
            var _b = _a[_i], key = _b[0], value = _b[1];
            if (!(key in attributeTypes)) {
                throw new TypeError(key + " attribute not in schema");
            }
        }
        res.page = ObjectSerializer_1.ObjectSerializer.serialize(data.page, "SLOListResponseMetadataPage", "");
        return res;
    };
    SLOListResponseMetadata.discriminator = undefined;
    SLOListResponseMetadata.attributeTypeMap = {
        "page": {
            "baseName": "page",
            "type": "SLOListResponseMetadataPage",
            "format": ""
        }
    };
    return SLOListResponseMetadata;
}());
exports.SLOListResponseMetadata = SLOListResponseMetadata;
//# sourceMappingURL=SLOListResponseMetadata.js.map