/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
* A JSON list of the ID or IDs of the Synthetic tests that you want to delete.
*/
export declare class SyntheticsDeleteTestsPayload {
    /**
    * An array of Synthetic test IDs you want to delete.
    */
    'publicIds'?: Array<string>;
    static readonly discriminator: string | undefined;
    static readonly attributeTypeMap: {
        [key: string]: {
            baseName: string;
            type: string;
            format: string;
        };
    };
    static getAttributeTypeMap(): {
        [key: string]: {
            baseName: string;
            type: string;
            format: string;
        };
    };
    static deserialize(data: {
        [key: string]: any;
    }): SyntheticsDeleteTestsPayload;
    static serialize(data: SyntheticsDeleteTestsPayload): {
        [key: string]: any;
    };
    constructor();
}
