"use strict";
/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TEXT = exports.JAVASCRIPT = exports.GLOBAL = exports.EMAIL = exports.ELEMENT = void 0;
exports.ELEMENT = 'element';
exports.EMAIL = 'email';
exports.GLOBAL = 'global';
exports.JAVASCRIPT = 'javascript';
exports.TEXT = 'text';
//# sourceMappingURL=SyntheticsBrowserVariableType.js.map