"use strict";
/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SyntheticsGetAPITestLatestResultsResponse = void 0;
var ObjectSerializer_1 = require("./ObjectSerializer");
/**
* Object with the latest Synthetic API test run.
*/
var SyntheticsGetAPITestLatestResultsResponse = /** @class */ (function () {
    function SyntheticsGetAPITestLatestResultsResponse() {
    }
    SyntheticsGetAPITestLatestResultsResponse.getAttributeTypeMap = function () {
        return SyntheticsGetAPITestLatestResultsResponse.attributeTypeMap;
    };
    SyntheticsGetAPITestLatestResultsResponse.deserialize = function (data) {
        var res = new SyntheticsGetAPITestLatestResultsResponse();
        res.lastTimestampFetched = ObjectSerializer_1.ObjectSerializer.deserialize(data.last_timestamp_fetched, "number", "int64");
        res.results = ObjectSerializer_1.ObjectSerializer.deserialize(data.results, "Array<SyntheticsAPITestResultShort>", "");
        return res;
    };
    SyntheticsGetAPITestLatestResultsResponse.serialize = function (data) {
        var attributeTypes = SyntheticsGetAPITestLatestResultsResponse.getAttributeTypeMap();
        var res = {};
        for (var _i = 0, _a = Object.entries(data); _i < _a.length; _i++) {
            var _b = _a[_i], key = _b[0], value = _b[1];
            if (!(key in attributeTypes)) {
                throw new TypeError(key + " attribute not in schema");
            }
        }
        res.last_timestamp_fetched = ObjectSerializer_1.ObjectSerializer.serialize(data.lastTimestampFetched, "number", "int64");
        res.results = ObjectSerializer_1.ObjectSerializer.serialize(data.results, "Array<SyntheticsAPITestResultShort>", "");
        return res;
    };
    SyntheticsGetAPITestLatestResultsResponse.discriminator = undefined;
    SyntheticsGetAPITestLatestResultsResponse.attributeTypeMap = {
        "lastTimestampFetched": {
            "baseName": "last_timestamp_fetched",
            "type": "number",
            "format": "int64"
        },
        "results": {
            "baseName": "results",
            "type": "Array<SyntheticsAPITestResultShort>",
            "format": ""
        }
    };
    return SyntheticsGetAPITestLatestResultsResponse;
}());
exports.SyntheticsGetAPITestLatestResultsResponse = SyntheticsGetAPITestLatestResultsResponse;
//# sourceMappingURL=SyntheticsGetAPITestLatestResultsResponse.js.map