/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
* Error code that can be returned by a Synthetic test.
*/
export declare type SyntheticsErrorCode = typeof NO_ERROR | typeof UNKNOWN | typeof DNS | typeof SSL | typeof TIMEOUT | typeof DENIED | typeof INCORRECT_ASSERTION;
export declare const NO_ERROR = "NO_ERROR";
export declare const UNKNOWN = "UNKNOWN";
export declare const DNS = "DNS";
export declare const SSL = "SSL";
export declare const TIMEOUT = "TIMEOUT";
export declare const DENIED = "DENIED";
export declare const INCORRECT_ASSERTION = "INCORRECT_ASSERTION";
