/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SyntheticsBrowserVariableType } from './SyntheticsBrowserVariableType';
import { HttpFile } from '../http/http';

/**
* Object defining a variable that can be used in your browser test. Learn more in the [Browser test Actions documentation](https://docs.datadoghq.com/synthetics/browser_tests/actions#variable).
*/
export class SyntheticsBrowserVariable {
    /**
    * Example for the variable.
    */
    'example'?: string;
    /**
    * ID for the variable.
    */
    'id'?: string;
    /**
    * Name of the variable.
    */
    'name': string;
    /**
    * Pattern of the variable.
    */
    'pattern'?: string;
    'type': SyntheticsBrowserVariableType;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "example",
            "baseName": "example",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "pattern",
            "baseName": "pattern",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "SyntheticsBrowserVariableType",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SyntheticsBrowserVariable.attributeTypeMap;
    }
    
    public constructor() {
    }
}

