/**
 * Datadog API V1 Collection
 * Collection of all Datadog Public endpoints.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@datadoghq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Tracing without limits usage for a given organization for a given hour.
*/
export class UsageTracingWithoutLimitsHour {
    /**
    * The hour for the usage.
    */
    'hour'?: Date;
    /**
    * Contains the total number of bytes ingested during a given hour.
    */
    'ingestedEventsBytes'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "hour",
            "baseName": "hour",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "ingestedEventsBytes",
            "baseName": "ingested_events_bytes",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return UsageTracingWithoutLimitsHour.attributeTypeMap;
    }
    
    public constructor() {
    }
}

