/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AttributeTypeMap } from "./ObjectSerializer";

/**
 * The object containing page total count.
 */

export class UsageCustomReportsPage {
  /**
   * Total page count.
   */
  "totalCount"?: number;

  "unparsedObject"?: any;

  static readonly attributeTypeMap: AttributeTypeMap = {
    totalCount: {
      baseName: "total_count",
      type: "number",
      format: "int64",
    },
  };

  static getAttributeTypeMap(): AttributeTypeMap {
    return UsageCustomReportsPage.attributeTypeMap;
  }

  public constructor() {}
}
