/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* The field to sort by.
*/
export type UsageAttributionSort = "api_percentage" | "snmp_usage" | "apm_host_usage" | "api_usage" | "container_usage" | "custom_timeseries_percentage" | "container_percentage" | "apm_host_percentage" | "npm_host_percentage" | "browser_percentage" | "browser_usage" | "infra_host_percentage" | "snmp_percentage" | "npm_host_usage" | "infra_host_usage" | "custom_timeseries_usage" | "lambda_functions_usage" | "lambda_functions_percentage" | "lambda_invocations_usage" | "lambda_invocations_percentage" | "lambda_usage" | "lambda_percentage" ;
