/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UsageCustomReportsData } from "./UsageCustomReportsData";
import { UsageCustomReportsMeta } from "./UsageCustomReportsMeta";
import { AttributeTypeMap } from "./ObjectSerializer";

/**
 * Response containing available custom reports.
 */

export class UsageCustomReportsResponse {
  /**
   * An array of available custom reports.
   */
  "data"?: Array<UsageCustomReportsData>;
  "meta"?: UsageCustomReportsMeta;

  "unparsedObject"?: any;

  static readonly attributeTypeMap: AttributeTypeMap = {
    data: {
      baseName: "data",
      type: "Array<UsageCustomReportsData>",
    },
    meta: {
      baseName: "meta",
      type: "UsageCustomReportsMeta",
    },
  };

  static getAttributeTypeMap(): AttributeTypeMap {
    return UsageCustomReportsResponse.attributeTypeMap;
  }

  public constructor() {}
}
