/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class UsageDBMHour {
  /**
   * The total number of Database Monitoring host hours from the start of the given hour’s month until the given hour.
   */
  "dbmHostCount"?: number;
  /**
   * The total number of normalized Database Monitoring queries from the start of the given hour’s month until the given hour.
   */
  "dbmQueriesCount"?: number;
  /**
   * The hour for the usage.
   */
  "hour"?: Date;

  "unparsedObject"?: any;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: {
    [key: string]: {
      name: string;
      baseName: string;
      type: string;
      required: boolean;
      format?: string;
      enumValues?: any;
    };
  } = {
    dbmHostCount: {
      name: "dbmHostCount",
      baseName: "dbm_host_count",
      type: "number",
      required: false,
      format: "int64",
    },
    dbmQueriesCount: {
      name: "dbmQueriesCount",
      baseName: "dbm_queries_count",
      type: "number",
      required: false,
      format: "int64",
    },
    hour: {
      name: "hour",
      baseName: "hour",
      type: "Date",
      required: false,
      format: "date-time",
    },
  };

  static getAttributeTypeMap() {
    return UsageDBMHour.attributeTypeMap;
  }

  public constructor() {}
}
