"use strict";
/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.UsageAttributionResponse = void 0;
var ObjectSerializer_1 = require("./ObjectSerializer");
/**
* Response containing the Usage Summary by tag(s).
*/
var UsageAttributionResponse = /** @class */ (function () {
    function UsageAttributionResponse() {
    }
    UsageAttributionResponse.getAttributeTypeMap = function () {
        return UsageAttributionResponse.attributeTypeMap;
    };
    UsageAttributionResponse.deserialize = function (data) {
        var res = new UsageAttributionResponse();
        res.metadata = ObjectSerializer_1.ObjectSerializer.deserialize(data.metadata, "UsageAttributionMetadata", "");
        res.usage = ObjectSerializer_1.ObjectSerializer.deserialize(data.usage, "Array<UsageAttributionBody>", "");
        return res;
    };
    UsageAttributionResponse.serialize = function (data) {
        var attributeTypes = UsageAttributionResponse.getAttributeTypeMap();
        var res = {};
        for (var _i = 0, _a = Object.entries(data); _i < _a.length; _i++) {
            var _b = _a[_i], key = _b[0], value = _b[1];
            if (!(key in attributeTypes)) {
                throw new TypeError(key + " attribute not in schema");
            }
        }
        res.metadata = ObjectSerializer_1.ObjectSerializer.serialize(data.metadata, "UsageAttributionMetadata", "");
        res.usage = ObjectSerializer_1.ObjectSerializer.serialize(data.usage, "Array<UsageAttributionBody>", "");
        return res;
    };
    UsageAttributionResponse.discriminator = undefined;
    UsageAttributionResponse.attributeTypeMap = {
        "metadata": {
            "baseName": "metadata",
            "type": "UsageAttributionMetadata",
            "format": ""
        },
        "usage": {
            "baseName": "usage",
            "type": "Array<UsageAttributionBody>",
            "format": ""
        }
    };
    return UsageAttributionResponse;
}());
exports.UsageAttributionResponse = UsageAttributionResponse;
//# sourceMappingURL=UsageAttributionResponse.js.map