/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AttributeTypeMap } from "./ObjectSerializer";

/**
 * The number of SNMP devices for each hour for a given organization.
 */

export class UsageSNMPHour {
  /**
   * The hour for the usage.
   */
  "hour"?: Date;
  /**
   * The organization name.
   */
  "orgName"?: string;
  /**
   * The organization public ID.
   */
  "publicId"?: string;
  /**
   * Contains the number of SNMP devices.
   */
  "snmpDevices"?: number;

  "unparsedObject"?: any;

  static readonly attributeTypeMap: AttributeTypeMap = {
    hour: {
      baseName: "hour",
      type: "Date",
      format: "date-time",
    },
    orgName: {
      baseName: "org_name",
      type: "string",
    },
    publicId: {
      baseName: "public_id",
      type: "string",
    },
    snmpDevices: {
      baseName: "snmp_devices",
      type: "number",
      format: "int64",
    },
  };

  static getAttributeTypeMap(): AttributeTypeMap {
    return UsageSNMPHour.attributeTypeMap;
  }

  public constructor() {}
}
