/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UsageLogsByIndexHour } from './UsageLogsByIndexHour';
import { HttpFile } from '../http/http';

/**
* Response containing the number of indexed logs for each hour and index for a given organization.
*/
export class UsageLogsByIndexResponse {
    /**
    * An array of objects regarding hourly usage of logs by index response.
    */
    'usage'?: Array<UsageLogsByIndexHour>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "usage",
            "baseName": "usage",
            "type": "Array<UsageLogsByIndexHour>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UsageLogsByIndexResponse.attributeTypeMap;
    }
    
    public constructor() {
    }
}

