/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class UsageAttributionValues {
  /**
   * The percentage of synthetic API test usage by tag(s).
   */
  "apiPercentage"?: number;
  /**
   * The synthetic API test usage by tag(s).
   */
  "apiUsage"?: number;
  /**
   * The percentage of APM host usage by tag(s).
   */
  "apmHostPercentage"?: number;
  /**
   * The APM host usage by tag(s).
   */
  "apmHostUsage"?: number;
  /**
   * The percentage of synthetic browser test usage by tag(s).
   */
  "browserPercentage"?: number;
  /**
   * The synthetic browser test usage by tag(s).
   */
  "browserUsage"?: number;
  /**
   * The percentage of container usage by tag(s).
   */
  "containerPercentage"?: number;
  /**
   * The container usage by tag(s).
   */
  "containerUsage"?: number;
  /**
   * The percentage of Cloud Security Posture Management container usage by tag(s)
   */
  "cspmContainerPercentage"?: number;
  /**
   * The Cloud Security Posture Management container usage by tag(s)
   */
  "cspmContainerUsage"?: number;
  /**
   * The percentage of Cloud Security Posture Management host usage by tag(s)
   */
  "cspmHostPercentage"?: number;
  /**
   * The Cloud Security Posture Management host usage by tag(s)
   */
  "cspmHostUsage"?: number;
  /**
   * The percentage of custom metrics usage by tag(s).
   */
  "customTimeseriesPercentage"?: number;
  /**
   * The custom metrics usage by tag(s).
   */
  "customTimeseriesUsage"?: number;
  /**
   * The percentage of Cloud Workload Security container usage by tag(s)
   */
  "cwsContainerPercentage"?: number;
  /**
   * The Cloud Workload Security container usage by tag(s)
   */
  "cwsContainerUsage"?: number;
  /**
   * The percentage of Cloud Workload Security host usage by tag(s)
   */
  "cwsHostPercentage"?: number;
  /**
   * The Cloud Workload Security host usage by tag(s)
   */
  "cwsHostUsage"?: number;
  /**
   * The percentage of Database Monitoring host usage by tag(s).
   */
  "dbmHostsPercentage"?: number;
  /**
   * The Database Monitoring host usage by tag(s).
   */
  "dbmHostsUsage"?: number;
  /**
   * The percentage of Database Monitoring normalized queries usage by tag(s).
   */
  "dbmQueriesPercentage"?: number;
  /**
   * The Database Monitoring normalized queries usage by tag(s).
   */
  "dbmQueriesUsage"?: number;
  /**
   * The percentage of infrastructure host usage by tag(s).
   */
  "infraHostPercentage"?: number;
  /**
   * The infrastructure host usage by tag(s).
   */
  "infraHostUsage"?: number;
  /**
   * The percentage of Lambda function usage by tag(s).
   */
  "lambdaFunctionsPercentage"?: number;
  /**
   * The Lambda function usage by tag(s).
   */
  "lambdaFunctionsUsage"?: number;
  /**
   * The percentage of Lambda invocation usage by tag(s).
   */
  "lambdaInvocationsPercentage"?: number;
  /**
   * The Lambda invocation usage by tag(s).
   */
  "lambdaInvocationsUsage"?: number;
  /**
   * The percentage of Lambda function usage by tag(s).  **Note** this field is deprecated. Use lambda_functions_percentage instead.
   */
  "lambdaPercentage"?: number;
  /**
   * The Lambda function usage by tag(s).  **Note** this field is deprecated. Use lambda_functions_usage instead.
   */
  "lambdaUsage"?: number;
  /**
   * The percentage of network host usage by tag(s).
   */
  "npmHostPercentage"?: number;
  /**
   * The network host usage by tag(s).
   */
  "npmHostUsage"?: number;
  /**
   * The percentage of profiled containers usage by tag(s).
   */
  "profiledContainerPercentage"?: number;
  /**
   * The profiled container usage by tag(s).
   */
  "profiledContainerUsage"?: number;
  /**
   * The percentage of profiled hosts usage by tag(s).
   */
  "profiledHostsPercentage"?: number;
  /**
   * The profiled host usage by tag(s).
   */
  "profiledHostsUsage"?: number;
  /**
   * The percentage of network device usage by tag(s).
   */
  "snmpPercentage"?: number;
  /**
   * The network device usage by tag(s).
   */
  "snmpUsage"?: number;

  "unparsedObject"?: any;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: {
    [key: string]: {
      name: string;
      baseName: string;
      type: string;
      required: boolean;
      format?: string;
    };
  } = {
    apiPercentage: {
      name: "apiPercentage",
      baseName: "api_percentage",
      type: "number",
      required: false,
      format: "double",
    },
    apiUsage: {
      name: "apiUsage",
      baseName: "api_usage",
      type: "number",
      required: false,
      format: "double",
    },
    apmHostPercentage: {
      name: "apmHostPercentage",
      baseName: "apm_host_percentage",
      type: "number",
      required: false,
      format: "double",
    },
    apmHostUsage: {
      name: "apmHostUsage",
      baseName: "apm_host_usage",
      type: "number",
      required: false,
      format: "double",
    },
    browserPercentage: {
      name: "browserPercentage",
      baseName: "browser_percentage",
      type: "number",
      required: false,
      format: "double",
    },
    browserUsage: {
      name: "browserUsage",
      baseName: "browser_usage",
      type: "number",
      required: false,
      format: "double",
    },
    containerPercentage: {
      name: "containerPercentage",
      baseName: "container_percentage",
      type: "number",
      required: false,
      format: "double",
    },
    containerUsage: {
      name: "containerUsage",
      baseName: "container_usage",
      type: "number",
      required: false,
      format: "double",
    },
    cspmContainerPercentage: {
      name: "cspmContainerPercentage",
      baseName: "cspm_container_percentage",
      type: "number",
      required: false,
      format: "double",
    },
    cspmContainerUsage: {
      name: "cspmContainerUsage",
      baseName: "cspm_container_usage",
      type: "number",
      required: false,
      format: "double",
    },
    cspmHostPercentage: {
      name: "cspmHostPercentage",
      baseName: "cspm_host_percentage",
      type: "number",
      required: false,
      format: "double",
    },
    cspmHostUsage: {
      name: "cspmHostUsage",
      baseName: "cspm_host_usage",
      type: "number",
      required: false,
      format: "double",
    },
    customTimeseriesPercentage: {
      name: "customTimeseriesPercentage",
      baseName: "custom_timeseries_percentage",
      type: "number",
      required: false,
      format: "double",
    },
    customTimeseriesUsage: {
      name: "customTimeseriesUsage",
      baseName: "custom_timeseries_usage",
      type: "number",
      required: false,
      format: "double",
    },
    cwsContainerPercentage: {
      name: "cwsContainerPercentage",
      baseName: "cws_container_percentage",
      type: "number",
      required: false,
      format: "double",
    },
    cwsContainerUsage: {
      name: "cwsContainerUsage",
      baseName: "cws_container_usage",
      type: "number",
      required: false,
      format: "double",
    },
    cwsHostPercentage: {
      name: "cwsHostPercentage",
      baseName: "cws_host_percentage",
      type: "number",
      required: false,
      format: "double",
    },
    cwsHostUsage: {
      name: "cwsHostUsage",
      baseName: "cws_host_usage",
      type: "number",
      required: false,
      format: "double",
    },
    dbmHostsPercentage: {
      name: "dbmHostsPercentage",
      baseName: "dbm_hosts_percentage",
      type: "number",
      required: false,
      format: "double",
    },
    dbmHostsUsage: {
      name: "dbmHostsUsage",
      baseName: "dbm_hosts_usage",
      type: "number",
      required: false,
      format: "double",
    },
    dbmQueriesPercentage: {
      name: "dbmQueriesPercentage",
      baseName: "dbm_queries_percentage",
      type: "number",
      required: false,
      format: "double",
    },
    dbmQueriesUsage: {
      name: "dbmQueriesUsage",
      baseName: "dbm_queries_usage",
      type: "number",
      required: false,
      format: "double",
    },
    infraHostPercentage: {
      name: "infraHostPercentage",
      baseName: "infra_host_percentage",
      type: "number",
      required: false,
      format: "double",
    },
    infraHostUsage: {
      name: "infraHostUsage",
      baseName: "infra_host_usage",
      type: "number",
      required: false,
      format: "double",
    },
    lambdaFunctionsPercentage: {
      name: "lambdaFunctionsPercentage",
      baseName: "lambda_functions_percentage",
      type: "number",
      required: false,
      format: "double",
    },
    lambdaFunctionsUsage: {
      name: "lambdaFunctionsUsage",
      baseName: "lambda_functions_usage",
      type: "number",
      required: false,
      format: "double",
    },
    lambdaInvocationsPercentage: {
      name: "lambdaInvocationsPercentage",
      baseName: "lambda_invocations_percentage",
      type: "number",
      required: false,
      format: "double",
    },
    lambdaInvocationsUsage: {
      name: "lambdaInvocationsUsage",
      baseName: "lambda_invocations_usage",
      type: "number",
      required: false,
      format: "double",
    },
    lambdaPercentage: {
      name: "lambdaPercentage",
      baseName: "lambda_percentage",
      type: "number",
      required: false,
      format: "double",
    },
    lambdaUsage: {
      name: "lambdaUsage",
      baseName: "lambda_usage",
      type: "number",
      required: false,
      format: "double",
    },
    npmHostPercentage: {
      name: "npmHostPercentage",
      baseName: "npm_host_percentage",
      type: "number",
      required: false,
      format: "double",
    },
    npmHostUsage: {
      name: "npmHostUsage",
      baseName: "npm_host_usage",
      type: "number",
      required: false,
      format: "double",
    },
    profiledContainerPercentage: {
      name: "profiledContainerPercentage",
      baseName: "profiled_container_percentage",
      type: "number",
      required: false,
      format: "double",
    },
    profiledContainerUsage: {
      name: "profiledContainerUsage",
      baseName: "profiled_container_usage",
      type: "number",
      required: false,
      format: "double",
    },
    profiledHostsPercentage: {
      name: "profiledHostsPercentage",
      baseName: "profiled_hosts_percentage",
      type: "number",
      required: false,
      format: "double",
    },
    profiledHostsUsage: {
      name: "profiledHostsUsage",
      baseName: "profiled_hosts_usage",
      type: "number",
      required: false,
      format: "double",
    },
    snmpPercentage: {
      name: "snmpPercentage",
      baseName: "snmp_percentage",
      type: "number",
      required: false,
      format: "double",
    },
    snmpUsage: {
      name: "snmpUsage",
      baseName: "snmp_usage",
      type: "number",
      required: false,
      format: "double",
    },
  };

  static getAttributeTypeMap() {
    return UsageAttributionValues.attributeTypeMap;
  }

  public constructor() {}
}
