/**
 * Datadog API V1 Collection
 * Collection of all Datadog Public endpoints.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@datadoghq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { WidgetComparator } from './WidgetComparator';
import { WidgetPalette } from './WidgetPalette';
import { HttpFile } from '../http/http';

/**
* Define a conditional format for the widget.
*/
export class WidgetConditionalFormat {
    'comparator': WidgetComparator;
    /**
    * Color palette to apply to the background, same values available as palette.
    */
    'customBgColor'?: string;
    /**
    * Color palette to apply to the foreground, same values available as palette.
    */
    'customFgColor'?: string;
    /**
    * True hides values.
    */
    'hideValue'?: boolean;
    /**
    * Displays an image as the background.
    */
    'imageUrl'?: string;
    /**
    * Metric from the request to correlate this conditional format with.
    */
    'metric'?: string;
    'palette': WidgetPalette;
    /**
    * Defines the displayed timeframe.
    */
    'timeframe'?: string;
    /**
    * Value for the comparator.
    */
    'value': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "comparator",
            "baseName": "comparator",
            "type": "WidgetComparator",
            "format": ""
        },
        {
            "name": "customBgColor",
            "baseName": "custom_bg_color",
            "type": "string",
            "format": ""
        },
        {
            "name": "customFgColor",
            "baseName": "custom_fg_color",
            "type": "string",
            "format": ""
        },
        {
            "name": "hideValue",
            "baseName": "hide_value",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "imageUrl",
            "baseName": "image_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "metric",
            "baseName": "metric",
            "type": "string",
            "format": ""
        },
        {
            "name": "palette",
            "baseName": "palette",
            "type": "WidgetPalette",
            "format": ""
        },
        {
            "name": "timeframe",
            "baseName": "timeframe",
            "type": "string",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "number",
            "format": "double"
        }    ];

    static getAttributeTypeMap() {
        return WidgetConditionalFormat.attributeTypeMap;
    }
    
    public constructor() {
    }
}

