/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* The available timeframes depend on the widget you are using.
*/
export type WidgetLiveSpan = "1m" | "5m" | "10m" | "15m" | "30m" | "1h" | "4h" | "1d" | "2d" | "1w" | "1mo" | "3mo" | "6mo" | "1y" | "alert" ;
