"use strict";
/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CENTER = exports.FIT = exports.ZOOM = exports.SCALEDOWN = exports.NONE = exports.COVER = exports.CONTAIN = exports.FILL = void 0;
exports.FILL = 'fill';
exports.CONTAIN = 'contain';
exports.COVER = 'cover';
exports.NONE = 'none';
exports.SCALEDOWN = 'scale-down';
exports.ZOOM = 'zoom';
exports.FIT = 'fit';
exports.CENTER = 'center';
//# sourceMappingURL=WidgetImageSizing.js.map