/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { APIKeyResponseIncludedItem } from "./APIKeyResponseIncludedItem";
import { PartialAPIKey } from "./PartialAPIKey";
import { ObjectSerializer } from "./ObjectSerializer";

/**
 * Response for a list of API keys.
 */

export class APIKeysResponse {
  /**
   * Array of API keys.
   */
  "data"?: Array<PartialAPIKey>;
  /**
   * Array of objects related to the API key.
   */
  "included"?: Array<APIKeyResponseIncludedItem>;

  "unparsedObject"?: any;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: {
    [key: string]: { baseName: string; type: string; format: string };
  } = {
    data: {
      baseName: "data",
      type: "Array<PartialAPIKey>",
      format: "",
    },
    included: {
      baseName: "included",
      type: "Array<APIKeyResponseIncludedItem>",
      format: "",
    },
  };

  static getAttributeTypeMap() {
    return APIKeysResponse.attributeTypeMap;
  }

  static deserialize(data: { [key: string]: any }): APIKeysResponse {
    const res = new APIKeysResponse();

    res.data = ObjectSerializer.deserialize(
      data.data,
      "Array<PartialAPIKey>",
      ""
    );

    res.included = ObjectSerializer.deserialize(
      data.included,
      "Array<APIKeyResponseIncludedItem>",
      ""
    );

    return res;
  }

  static serialize(data: APIKeysResponse): { [key: string]: any } {
    const attributeTypes = APIKeysResponse.getAttributeTypeMap();
    const res: { [index: string]: any } = {};
    for (const [key, value] of Object.entries(data)) {
      if (!(key in attributeTypes)) {
        throw new TypeError(`${key} attribute not in schema`);
      }
    }
    if (data?.unparsedObject !== undefined) {
      return data.unparsedObject;
    }
    res.data = ObjectSerializer.serialize(
      data.data,
      "Array<PartialAPIKey>",
      ""
    );

    res.included = ObjectSerializer.serialize(
      data.included,
      "Array<APIKeyResponseIncludedItem>",
      ""
    );

    return res;
  }

  public constructor() {}
}
