"use strict";
/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DashboardListItems = void 0;
var ObjectSerializer_1 = require("./ObjectSerializer");
/**
* Dashboards within a list.
*/
var DashboardListItems = /** @class */ (function () {
    function DashboardListItems() {
    }
    DashboardListItems.getAttributeTypeMap = function () {
        return DashboardListItems.attributeTypeMap;
    };
    DashboardListItems.deserialize = function (data) {
        var res = new DashboardListItems();
        if (data.dashboards === undefined) {
            throw new TypeError("missing required attribute 'dashboards' on 'DashboardListItems' object");
        }
        res.dashboards = ObjectSerializer_1.ObjectSerializer.deserialize(data.dashboards, "Array<DashboardListItem>", "");
        res.total = ObjectSerializer_1.ObjectSerializer.deserialize(data.total, "number", "int64");
        return res;
    };
    DashboardListItems.serialize = function (data) {
        var attributeTypes = DashboardListItems.getAttributeTypeMap();
        var res = {};
        for (var _i = 0, _a = Object.entries(data); _i < _a.length; _i++) {
            var _b = _a[_i], key = _b[0], value = _b[1];
            if (!(key in attributeTypes)) {
                throw new TypeError(key + " attribute not in schema");
            }
        }
        if (data.dashboards === undefined) {
            throw new TypeError("missing required attribute 'dashboards' on 'DashboardListItems' object");
        }
        res.dashboards = ObjectSerializer_1.ObjectSerializer.serialize(data.dashboards, "Array<DashboardListItem>", "");
        res.total = ObjectSerializer_1.ObjectSerializer.serialize(data.total, "number", "int64");
        return res;
    };
    DashboardListItems.discriminator = undefined;
    DashboardListItems.attributeTypeMap = {
        "dashboards": {
            "baseName": "dashboards",
            "type": "Array<DashboardListItem>",
            "format": ""
        },
        "total": {
            "baseName": "total",
            "type": "number",
            "format": "int64"
        }
    };
    return DashboardListItems;
}());
exports.DashboardListItems = DashboardListItems;
//# sourceMappingURL=DashboardListItems.js.map