/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
* The type of the dashboard.
*/
export declare type DashboardType = typeof CUSTOM_TIMEBOARD | typeof CUSTOM_SCREENBOARD | typeof INTEGRATION_SCREENBOARD | typeof INTEGRATION_TIMEBOARD | typeof HOST_TIMEBOARD;
export declare const CUSTOM_TIMEBOARD = "custom_timeboard";
export declare const CUSTOM_SCREENBOARD = "custom_screenboard";
export declare const INTEGRATION_SCREENBOARD = "integration_screenboard";
export declare const INTEGRATION_TIMEBOARD = "integration_timeboard";
export declare const HOST_TIMEBOARD = "host_timeboard";
