"use strict";
/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DashboardListItemResponse = void 0;
var ObjectSerializer_1 = require("./ObjectSerializer");
/**
* A dashboard within a list.
*/
var DashboardListItemResponse = /** @class */ (function () {
    function DashboardListItemResponse() {
    }
    DashboardListItemResponse.getAttributeTypeMap = function () {
        return DashboardListItemResponse.attributeTypeMap;
    };
    DashboardListItemResponse.deserialize = function (data) {
        var res = new DashboardListItemResponse();
        if (data.id === undefined) {
            throw new TypeError("missing required attribute 'id' on 'DashboardListItemResponse' object");
        }
        res.id = ObjectSerializer_1.ObjectSerializer.deserialize(data.id, "string", "");
        if (data.type === undefined) {
            throw new TypeError("missing required attribute 'type' on 'DashboardListItemResponse' object");
        }
        if (['custom_timeboard', 'custom_screenboard', 'integration_screenboard', 'integration_timeboard', 'host_timeboard', undefined].includes(data.type)) {
            res.type = data.type;
        }
        else {
            throw TypeError("invalid enum value " + data.type + " for type");
        }
        return res;
    };
    DashboardListItemResponse.serialize = function (data) {
        var attributeTypes = DashboardListItemResponse.getAttributeTypeMap();
        var res = {};
        for (var _i = 0, _a = Object.entries(data); _i < _a.length; _i++) {
            var _b = _a[_i], key = _b[0], value = _b[1];
            if (!(key in attributeTypes)) {
                throw new TypeError(key + " attribute not in schema");
            }
        }
        if (data.id === undefined) {
            throw new TypeError("missing required attribute 'id' on 'DashboardListItemResponse' object");
        }
        res.id = ObjectSerializer_1.ObjectSerializer.serialize(data.id, "string", "");
        if (data.type === undefined) {
            throw new TypeError("missing required attribute 'type' on 'DashboardListItemResponse' object");
        }
        if (['custom_timeboard', 'custom_screenboard', 'integration_screenboard', 'integration_timeboard', 'host_timeboard', undefined].includes(data.type)) {
            res.type = data.type;
        }
        else {
            throw TypeError("invalid enum value " + data.type + " for type");
        }
        return res;
    };
    DashboardListItemResponse.discriminator = undefined;
    DashboardListItemResponse.attributeTypeMap = {
        "id": {
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        "type": {
            "baseName": "type",
            "type": "DashboardType",
            "format": ""
        }
    };
    return DashboardListItemResponse;
}());
exports.DashboardListItemResponse = DashboardListItemResponse;
//# sourceMappingURL=DashboardListItemResponse.js.map