/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 */

export type DashboardReportScheduleRepeatAt =
  | typeof DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_00_00
  | typeof DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_00_30
  | typeof DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_01_00
  | typeof DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_01_30
  | typeof DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_02_00
  | typeof DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_02_30
  | typeof DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_03_00
  | typeof DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_03_30
  | typeof DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_04_00
  | typeof DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_04_30
  | typeof DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_05_00
  | typeof DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_05_30
  | typeof DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_06_00
  | typeof DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_06_30
  | typeof DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_07_00
  | typeof DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_07_30
  | typeof DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_08_00
  | typeof DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_08_30
  | typeof DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_09_00
  | typeof DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_09_30
  | typeof DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_10_00
  | typeof DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_10_30
  | typeof DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_11_00
  | typeof DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_11_30
  | typeof DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_12_00
  | typeof DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_12_30
  | typeof DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_13_00
  | typeof DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_13_30
  | typeof DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_14_00
  | typeof DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_14_30
  | typeof DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_15_00
  | typeof DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_15_30
  | typeof DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_16_00
  | typeof DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_16_30
  | typeof DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_17_00
  | typeof DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_17_30
  | typeof DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_18_00
  | typeof DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_18_30
  | typeof DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_19_00
  | typeof DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_19_30
  | typeof DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_20_00
  | typeof DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_20_30
  | typeof DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_21_00
  | typeof DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_21_30
  | typeof DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_22_00
  | typeof DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_22_30
  | typeof DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_23_00
  | typeof DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_23_30;
export const DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_00_00 = "00:00";
export const DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_00_30 = "00:30";
export const DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_01_00 = "01:00";
export const DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_01_30 = "01:30";
export const DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_02_00 = "02:00";
export const DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_02_30 = "02:30";
export const DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_03_00 = "03:00";
export const DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_03_30 = "03:30";
export const DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_04_00 = "04:00";
export const DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_04_30 = "04:30";
export const DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_05_00 = "05:00";
export const DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_05_30 = "05:30";
export const DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_06_00 = "06:00";
export const DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_06_30 = "06:30";
export const DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_07_00 = "07:00";
export const DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_07_30 = "07:30";
export const DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_08_00 = "08:00";
export const DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_08_30 = "08:30";
export const DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_09_00 = "09:00";
export const DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_09_30 = "09:30";
export const DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_10_00 = "10:00";
export const DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_10_30 = "10:30";
export const DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_11_00 = "11:00";
export const DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_11_30 = "11:30";
export const DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_12_00 = "12:00";
export const DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_12_30 = "12:30";
export const DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_13_00 = "13:00";
export const DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_13_30 = "13:30";
export const DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_14_00 = "14:00";
export const DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_14_30 = "14:30";
export const DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_15_00 = "15:00";
export const DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_15_30 = "15:30";
export const DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_16_00 = "16:00";
export const DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_16_30 = "16:30";
export const DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_17_00 = "17:00";
export const DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_17_30 = "17:30";
export const DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_18_00 = "18:00";
export const DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_18_30 = "18:30";
export const DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_19_00 = "19:00";
export const DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_19_30 = "19:30";
export const DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_20_00 = "20:00";
export const DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_20_30 = "20:30";
export const DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_21_00 = "21:00";
export const DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_21_30 = "21:30";
export const DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_22_00 = "22:00";
export const DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_22_30 = "22:30";
export const DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_23_00 = "23:00";
export const DASHBOARD_REPORT_SCHEDULE_REPEAT_AT_23_30 = "23:30";
