/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 */

export type DashboardReportScheduleFrequency =
  | typeof DASHBOARD_REPORT_SCHEDULE_FREQUENCY_1D
  | typeof DASHBOARD_REPORT_SCHEDULE_FREQUENCY_2D
  | typeof DASHBOARD_REPORT_SCHEDULE_FREQUENCY_3D
  | typeof DASHBOARD_REPORT_SCHEDULE_FREQUENCY_4D
  | typeof DASHBOARD_REPORT_SCHEDULE_FREQUENCY_5D
  | typeof DASHBOARD_REPORT_SCHEDULE_FREQUENCY_6D
  | typeof DASHBOARD_REPORT_SCHEDULE_FREQUENCY_1W
  | typeof DASHBOARD_REPORT_SCHEDULE_FREQUENCY_2W
  | typeof DASHBOARD_REPORT_SCHEDULE_FREQUENCY_3W
  | typeof DASHBOARD_REPORT_SCHEDULE_FREQUENCY_1MO
  | typeof DASHBOARD_REPORT_SCHEDULE_FREQUENCY_2MO
  | typeof DASHBOARD_REPORT_SCHEDULE_FREQUENCY_3MO
  | typeof DASHBOARD_REPORT_SCHEDULE_FREQUENCY_4MO
  | typeof DASHBOARD_REPORT_SCHEDULE_FREQUENCY_5MO
  | typeof DASHBOARD_REPORT_SCHEDULE_FREQUENCY_6MO
  | typeof DASHBOARD_REPORT_SCHEDULE_FREQUENCY_7MO
  | typeof DASHBOARD_REPORT_SCHEDULE_FREQUENCY_8MO
  | typeof DASHBOARD_REPORT_SCHEDULE_FREQUENCY_9MO
  | typeof DASHBOARD_REPORT_SCHEDULE_FREQUENCY_10MO
  | typeof DASHBOARD_REPORT_SCHEDULE_FREQUENCY_11MO
  | typeof DASHBOARD_REPORT_SCHEDULE_FREQUENCY_12MO;
export const DASHBOARD_REPORT_SCHEDULE_FREQUENCY_1D = "1d";
export const DASHBOARD_REPORT_SCHEDULE_FREQUENCY_2D = "2d";
export const DASHBOARD_REPORT_SCHEDULE_FREQUENCY_3D = "3d";
export const DASHBOARD_REPORT_SCHEDULE_FREQUENCY_4D = "4d";
export const DASHBOARD_REPORT_SCHEDULE_FREQUENCY_5D = "5d";
export const DASHBOARD_REPORT_SCHEDULE_FREQUENCY_6D = "6d";
export const DASHBOARD_REPORT_SCHEDULE_FREQUENCY_1W = "1w";
export const DASHBOARD_REPORT_SCHEDULE_FREQUENCY_2W = "2w";
export const DASHBOARD_REPORT_SCHEDULE_FREQUENCY_3W = "3w";
export const DASHBOARD_REPORT_SCHEDULE_FREQUENCY_1MO = "1mo";
export const DASHBOARD_REPORT_SCHEDULE_FREQUENCY_2MO = "2mo";
export const DASHBOARD_REPORT_SCHEDULE_FREQUENCY_3MO = "3mo";
export const DASHBOARD_REPORT_SCHEDULE_FREQUENCY_4MO = "4mo";
export const DASHBOARD_REPORT_SCHEDULE_FREQUENCY_5MO = "5mo";
export const DASHBOARD_REPORT_SCHEDULE_FREQUENCY_6MO = "6mo";
export const DASHBOARD_REPORT_SCHEDULE_FREQUENCY_7MO = "7mo";
export const DASHBOARD_REPORT_SCHEDULE_FREQUENCY_8MO = "8mo";
export const DASHBOARD_REPORT_SCHEDULE_FREQUENCY_9MO = "9mo";
export const DASHBOARD_REPORT_SCHEDULE_FREQUENCY_10MO = "10mo";
export const DASHBOARD_REPORT_SCHEDULE_FREQUENCY_11MO = "11mo";
export const DASHBOARD_REPORT_SCHEDULE_FREQUENCY_12MO = "12mo";
