/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ApplicationKeyRelationships } from './ApplicationKeyRelationships';
import { ApplicationKeysType } from './ApplicationKeysType';
import { FullApplicationKeyAttributes } from './FullApplicationKeyAttributes';
import { HttpFile } from '../http/http';

/**
* Datadog application key.
*/
export class FullApplicationKey {
    'attributes'?: FullApplicationKeyAttributes;
    /**
    * ID of the application key.
    */
    'id'?: string;
    'relationships'?: ApplicationKeyRelationships;
    'type'?: ApplicationKeysType;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "FullApplicationKeyAttributes",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "ApplicationKeyRelationships",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ApplicationKeysType",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FullApplicationKey.attributeTypeMap;
    }
    
    public constructor() {
    }
}

