/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IncidentTeamIncludedItems } from './IncidentTeamIncludedItems';
import { IncidentTeamResponseData } from './IncidentTeamResponseData';
import { HttpFile } from '../http/http';

/**
* Response with an incident team payload.
*/
export class IncidentTeamResponse {
    'data': IncidentTeamResponseData;
    /**
    * Included objects from relationships.
    */
    'included'?: Array<IncidentTeamIncludedItems>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "IncidentTeamResponseData",
            "format": ""
        },
        {
            "name": "included",
            "baseName": "included",
            "type": "Array<IncidentTeamIncludedItems>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IncidentTeamResponse.attributeTypeMap;
    }
    
    public constructor() {
    }
}

