/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IncidentFieldAttributesValueType } from './IncidentFieldAttributesValueType';
import { HttpFile } from '../http/http';

/**
* A field with potentially multiple values selected.
*/
export class IncidentFieldAttributesMultipleValue {
    'type'?: IncidentFieldAttributesValueType;
    /**
    * The multiple values selected for this field.
    */
    'value'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "IncidentFieldAttributesValueType",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IncidentFieldAttributesMultipleValue.attributeTypeMap;
    }
    
    public constructor() {
    }
}

