"use strict";
/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IncidentTeamCreateData = void 0;
var ObjectSerializer_1 = require("./ObjectSerializer");
/**
* Incident Team data for a create request.
*/
var IncidentTeamCreateData = /** @class */ (function () {
    function IncidentTeamCreateData() {
    }
    IncidentTeamCreateData.getAttributeTypeMap = function () {
        return IncidentTeamCreateData.attributeTypeMap;
    };
    IncidentTeamCreateData.deserialize = function (data) {
        var res = new IncidentTeamCreateData();
        res.attributes = ObjectSerializer_1.ObjectSerializer.deserialize(data.attributes, "IncidentTeamCreateAttributes", "");
        res.relationships = ObjectSerializer_1.ObjectSerializer.deserialize(data.relationships, "IncidentTeamRelationships", "");
        if (data.type === undefined) {
            throw new TypeError("missing required attribute 'type' on 'IncidentTeamCreateData' object");
        }
        if (['teams', undefined].includes(data.type)) {
            res.type = data.type;
        }
        else {
            throw TypeError("invalid enum value " + data.type + " for type");
        }
        return res;
    };
    IncidentTeamCreateData.serialize = function (data) {
        var attributeTypes = IncidentTeamCreateData.getAttributeTypeMap();
        var res = {};
        for (var _i = 0, _a = Object.entries(data); _i < _a.length; _i++) {
            var _b = _a[_i], key = _b[0], value = _b[1];
            if (!(key in attributeTypes)) {
                throw new TypeError(key + " attribute not in schema");
            }
        }
        res.attributes = ObjectSerializer_1.ObjectSerializer.serialize(data.attributes, "IncidentTeamCreateAttributes", "");
        res.relationships = ObjectSerializer_1.ObjectSerializer.serialize(data.relationships, "IncidentTeamRelationships", "");
        if (data.type === undefined) {
            throw new TypeError("missing required attribute 'type' on 'IncidentTeamCreateData' object");
        }
        if (['teams', undefined].includes(data.type)) {
            res.type = data.type;
        }
        else {
            throw TypeError("invalid enum value " + data.type + " for type");
        }
        return res;
    };
    IncidentTeamCreateData.discriminator = undefined;
    IncidentTeamCreateData.attributeTypeMap = {
        "attributes": {
            "baseName": "attributes",
            "type": "IncidentTeamCreateAttributes",
            "format": ""
        },
        "relationships": {
            "baseName": "relationships",
            "type": "IncidentTeamRelationships",
            "format": ""
        },
        "type": {
            "baseName": "type",
            "type": "IncidentTeamType",
            "format": ""
        }
    };
    return IncidentTeamCreateData;
}());
exports.IncidentTeamCreateData = IncidentTeamCreateData;
//# sourceMappingURL=IncidentTeamCreateData.js.map