/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LogsArchiveDestinationGCSType } from "./LogsArchiveDestinationGCSType";
import { LogsArchiveIntegrationGCS } from "./LogsArchiveIntegrationGCS";

export class LogsArchiveDestinationGCS {
  /**
   * The bucket where the archive will be stored.
   */
  "bucket": string;
  "integration": LogsArchiveIntegrationGCS;
  /**
   * The archive path.
   */
  "path"?: string;
  "type": LogsArchiveDestinationGCSType;

  "unparsedObject"?: any;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: {
    [key: string]: {
      name: string;
      baseName: string;
      type: string;
      required: boolean;
      format?: string;
      enumValues?: any;
    };
  } = {
    bucket: {
      name: "bucket",
      baseName: "bucket",
      type: "string",
      required: true,
      format: "",
    },
    integration: {
      name: "integration",
      baseName: "integration",
      type: "LogsArchiveIntegrationGCS",
      required: true,
      format: "",
    },
    path: {
      name: "path",
      baseName: "path",
      type: "string",
      required: false,
      format: "",
    },
    type: {
      name: "type",
      baseName: "type",
      type: "LogsArchiveDestinationGCSType",
      required: true,
      format: "",
    },
  };

  static getAttributeTypeMap() {
    return LogsArchiveDestinationGCS.attributeTypeMap;
  }

  public constructor() {}
}
