/**
 * Datadog API V2 Collection
 * Collection of all Datadog Public endpoints.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@datadoghq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LogsAggregateBucketValueTimeseriesPoint } from './LogsAggregateBucketValueTimeseriesPoint';
import { HttpFile } from '../http/http';

/**
* A timeseries array
*/
export class LogsAggregateBucketValueTimeseries extends Array<LogsAggregateBucketValueTimeseriesPoint> {

    static readonly discriminator: string | undefined = undefined;

    
    public constructor() {
        super();
    }
}

