/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LogsAggregateBucket } from './LogsAggregateBucket';
import { HttpFile } from '../http/http';

/**
* The query results
*/
export class LogsAggregateResponseData {
    /**
    * The list of matching buckets, one item per bucket
    */
    'buckets'?: Array<LogsAggregateBucket>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "buckets",
            "baseName": "buckets",
            "type": "Array<LogsAggregateBucket>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LogsAggregateResponseData.attributeTypeMap;
    }
    
    public constructor() {
    }
}

