"use strict";
/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.WORKING_AUTH_LEGACY = exports.FAILING = exports.WORKING = exports.UNKNOWN = void 0;
exports.UNKNOWN = 'UNKNOWN';
exports.WORKING = 'WORKING';
exports.FAILING = 'FAILING';
exports.WORKING_AUTH_LEGACY = 'WORKING_AUTH_LEGACY';
//# sourceMappingURL=LogsArchiveState.js.map