/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';
import { AttributeTypeMap, UnparsedObject } from './ObjectSerializer';

/**
* The Azure archive's integration destination.
*/

export class LogsArchiveIntegrationAzure {
    /**
    * A client ID.
    */
    'clientId': string;
    /**
    * A tenant ID.
    */
    'tenantId': string;

    'unparsedObject'?:any;

    static readonly attributeTypeMap: AttributeTypeMap = {
        "clientId": {
            "baseName": "client_id",
            "type": "string",
            "required": true,
            
        },
        "tenantId": {
            "baseName": "tenant_id",
            "type": "string",
            "required": true,
            
        }    };

    static getAttributeTypeMap(): AttributeTypeMap {
        return LogsArchiveIntegrationAzure.attributeTypeMap;
    }

    public constructor() {
    }
}



