"use strict";
/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.LogsListRequest = void 0;
var ObjectSerializer_1 = require("./ObjectSerializer");
/**
* The request for a logs list.
*/
var LogsListRequest = /** @class */ (function () {
    function LogsListRequest() {
    }
    LogsListRequest.getAttributeTypeMap = function () {
        return LogsListRequest.attributeTypeMap;
    };
    LogsListRequest.deserialize = function (data) {
        var res = new LogsListRequest();
        res.filter = ObjectSerializer_1.ObjectSerializer.deserialize(data.filter, "LogsQueryFilter", "");
        res.options = ObjectSerializer_1.ObjectSerializer.deserialize(data.options, "LogsQueryOptions", "");
        res.page = ObjectSerializer_1.ObjectSerializer.deserialize(data.page, "LogsListRequestPage", "");
        if (['timestamp', '-timestamp', undefined].includes(data.sort)) {
            res.sort = data.sort;
        }
        else {
            throw TypeError("invalid enum value " + data.sort + " for sort");
        }
        return res;
    };
    LogsListRequest.serialize = function (data) {
        var attributeTypes = LogsListRequest.getAttributeTypeMap();
        var res = {};
        for (var _i = 0, _a = Object.entries(data); _i < _a.length; _i++) {
            var _b = _a[_i], key = _b[0], value = _b[1];
            if (!(key in attributeTypes)) {
                throw new TypeError(key + " attribute not in schema");
            }
        }
        res.filter = ObjectSerializer_1.ObjectSerializer.serialize(data.filter, "LogsQueryFilter", "");
        res.options = ObjectSerializer_1.ObjectSerializer.serialize(data.options, "LogsQueryOptions", "");
        res.page = ObjectSerializer_1.ObjectSerializer.serialize(data.page, "LogsListRequestPage", "");
        if (['timestamp', '-timestamp', undefined].includes(data.sort)) {
            res.sort = data.sort;
        }
        else {
            throw TypeError("invalid enum value " + data.sort + " for sort");
        }
        return res;
    };
    LogsListRequest.discriminator = undefined;
    LogsListRequest.attributeTypeMap = {
        "filter": {
            "baseName": "filter",
            "type": "LogsQueryFilter",
            "format": ""
        },
        "options": {
            "baseName": "options",
            "type": "LogsQueryOptions",
            "format": ""
        },
        "page": {
            "baseName": "page",
            "type": "LogsListRequestPage",
            "format": ""
        },
        "sort": {
            "baseName": "sort",
            "type": "LogsSort",
            "format": ""
        }
    };
    return LogsListRequest;
}());
exports.LogsListRequest = LogsListRequest;
//# sourceMappingURL=LogsListRequest.js.map