"use strict";
/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.LogsArchiveCreateRequestAttributes = void 0;
var ObjectSerializer_1 = require("./ObjectSerializer");
/**
* The attributes associated with the archive.
*/
var LogsArchiveCreateRequestAttributes = /** @class */ (function () {
    function LogsArchiveCreateRequestAttributes() {
    }
    LogsArchiveCreateRequestAttributes.getAttributeTypeMap = function () {
        return LogsArchiveCreateRequestAttributes.attributeTypeMap;
    };
    LogsArchiveCreateRequestAttributes.deserialize = function (data) {
        var res = new LogsArchiveCreateRequestAttributes();
        if (data.destination === undefined) {
            throw new TypeError("missing required attribute 'destination' on 'LogsArchiveCreateRequestAttributes' object");
        }
        res.destination = ObjectSerializer_1.ObjectSerializer.deserialize(data.destination, "LogsArchiveCreateRequestDestination", "");
        res.includeTags = ObjectSerializer_1.ObjectSerializer.deserialize(data.include_tags, "boolean", "");
        if (data.name === undefined) {
            throw new TypeError("missing required attribute 'name' on 'LogsArchiveCreateRequestAttributes' object");
        }
        res.name = ObjectSerializer_1.ObjectSerializer.deserialize(data.name, "string", "");
        if (data.query === undefined) {
            throw new TypeError("missing required attribute 'query' on 'LogsArchiveCreateRequestAttributes' object");
        }
        res.query = ObjectSerializer_1.ObjectSerializer.deserialize(data.query, "string", "");
        res.rehydrationTags = ObjectSerializer_1.ObjectSerializer.deserialize(data.rehydration_tags, "Array<string>", "");
        return res;
    };
    LogsArchiveCreateRequestAttributes.serialize = function (data) {
        var attributeTypes = LogsArchiveCreateRequestAttributes.getAttributeTypeMap();
        var res = {};
        for (var _i = 0, _a = Object.entries(data); _i < _a.length; _i++) {
            var _b = _a[_i], key = _b[0], value = _b[1];
            if (!(key in attributeTypes)) {
                throw new TypeError(key + " attribute not in schema");
            }
        }
        if (data.destination === undefined) {
            throw new TypeError("missing required attribute 'destination' on 'LogsArchiveCreateRequestAttributes' object");
        }
        res.destination = ObjectSerializer_1.ObjectSerializer.serialize(data.destination, "LogsArchiveCreateRequestDestination", "");
        res.include_tags = ObjectSerializer_1.ObjectSerializer.serialize(data.includeTags, "boolean", "");
        if (data.name === undefined) {
            throw new TypeError("missing required attribute 'name' on 'LogsArchiveCreateRequestAttributes' object");
        }
        res.name = ObjectSerializer_1.ObjectSerializer.serialize(data.name, "string", "");
        if (data.query === undefined) {
            throw new TypeError("missing required attribute 'query' on 'LogsArchiveCreateRequestAttributes' object");
        }
        res.query = ObjectSerializer_1.ObjectSerializer.serialize(data.query, "string", "");
        res.rehydration_tags = ObjectSerializer_1.ObjectSerializer.serialize(data.rehydrationTags, "Array<string>", "");
        return res;
    };
    LogsArchiveCreateRequestAttributes.discriminator = undefined;
    LogsArchiveCreateRequestAttributes.attributeTypeMap = {
        "destination": {
            "baseName": "destination",
            "type": "LogsArchiveCreateRequestDestination",
            "format": ""
        },
        "includeTags": {
            "baseName": "include_tags",
            "type": "boolean",
            "format": ""
        },
        "name": {
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        "query": {
            "baseName": "query",
            "type": "string",
            "format": ""
        },
        "rehydrationTags": {
            "baseName": "rehydration_tags",
            "type": "Array<string>",
            "format": ""
        }
    };
    return LogsArchiveCreateRequestAttributes;
}());
exports.LogsArchiveCreateRequestAttributes = LogsArchiveCreateRequestAttributes;
//# sourceMappingURL=LogsArchiveCreateRequestAttributes.js.map