/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LogsAggregateResponseData } from "./LogsAggregateResponseData";
import { LogsResponseMetadata } from "./LogsResponseMetadata";
import { AttributeTypeMap } from "./ObjectSerializer";

/**
 * The response object for the logs aggregate API endpoint
 */

export class LogsAggregateResponse {
  "data"?: LogsAggregateResponseData;
  "meta"?: LogsResponseMetadata;

  "unparsedObject"?: any;

  static readonly attributeTypeMap: AttributeTypeMap = {
    data: {
      baseName: "data",
      type: "LogsAggregateResponseData",
    },
    meta: {
      baseName: "meta",
      type: "LogsResponseMetadata",
    },
  };

  static getAttributeTypeMap(): AttributeTypeMap {
    return LogsAggregateResponse.attributeTypeMap;
  }

  public constructor() {}
}
