/**
 * Datadog API V2 Collection
 * Collection of all Datadog Public endpoints.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@datadoghq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LogsMetricCompute } from './LogsMetricCompute';
import { LogsMetricFilter } from './LogsMetricFilter';
import { LogsMetricGroupBy } from './LogsMetricGroupBy';
import { HttpFile } from '../http/http';

/**
* The object describing the Datadog log-based metric to create.
*/
export class LogsMetricCreateAttributes {
    'compute': LogsMetricCompute;
    'filter'?: LogsMetricFilter;
    /**
    * The rules for the group by.
    */
    'groupBy'?: Array<LogsMetricGroupBy>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "compute",
            "baseName": "compute",
            "type": "LogsMetricCompute",
            "format": ""
        },
        {
            "name": "filter",
            "baseName": "filter",
            "type": "LogsMetricFilter",
            "format": ""
        },
        {
            "name": "groupBy",
            "baseName": "group_by",
            "type": "Array<LogsMetricGroupBy>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LogsMetricCreateAttributes.attributeTypeMap;
    }
    
    public constructor() {
    }
}

