/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class LogsWarning {
  /**
   * A unique code for this type of warning
   */
  "code"?: string;
  /**
   * A detailed explanation of this specific warning
   */
  "detail"?: string;
  /**
   * A short human-readable summary of the warning
   */
  "title"?: string;

  "unparsedObject"?: any;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: {
    [key: string]: {
      name: string;
      baseName: string;
      type: string;
      required: boolean;
      format?: string;
    };
  } = {
    code: {
      name: "code",
      baseName: "code",
      type: "string",
      required: false,
    },
    detail: {
      name: "detail",
      baseName: "detail",
      type: "string",
      required: false,
    },
    title: {
      name: "title",
      baseName: "title",
      type: "string",
      required: false,
    },
  };

  static getAttributeTypeMap() {
    return LogsWarning.attributeTypeMap;
  }

  public constructor() {}
}
