/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
* Object containing the definition of a metric's ingested and indexed volume.
*/
export declare class MetricIngestedIndexedVolumeAttributes {
    /**
    * Indexed volume for the given metric.
    */
    'indexedVolume'?: number;
    /**
    * Ingested volume for the given metric.
    */
    'ingestedVolume'?: number;
    static readonly discriminator: string | undefined;
    static readonly attributeTypeMap: {
        [key: string]: {
            baseName: string;
            type: string;
            format: string;
        };
    };
    static getAttributeTypeMap(): {
        [key: string]: {
            baseName: string;
            type: string;
            format: string;
        };
    };
    static deserialize(data: {
        [key: string]: any;
    }): MetricIngestedIndexedVolumeAttributes;
    static serialize(data: MetricIngestedIndexedVolumeAttributes): {
        [key: string]: any;
    };
    constructor();
}
