/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MetricDistinctVolume } from "./MetricDistinctVolume";
import { MetricIngestedIndexedVolume } from "./MetricIngestedIndexedVolume";
import { UnparsedObject } from "./ObjectSerializer";

/**
 * Possible response objects for a metric's volume.
 */

export type MetricVolumes =
  | MetricDistinctVolume
  | MetricIngestedIndexedVolume
  | UnparsedObject;
