/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
* The metric's type.
*/
export declare type MetricTagConfigurationMetricTypes = typeof GAUGE | typeof COUNT | typeof RATE | typeof DISTRIBUTION;
export declare const GAUGE = "gauge";
export declare const COUNT = "count";
export declare const RATE = "rate";
export declare const DISTRIBUTION = "distribution";
