/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IncidentIntegrationMetadataType } from './IncidentIntegrationMetadataType';
import { HttpFile } from '../http/http';

/**
* A relationship reference for an integration metadata object.
*/
export class RelationshipToIncidentIntegrationMetadataData {
    /**
    * A unique identifier that represents the integration metadata.
    */
    'id': string;
    'type': IncidentIntegrationMetadataType;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "IncidentIntegrationMetadataType",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RelationshipToIncidentIntegrationMetadataData.attributeTypeMap;
    }
    
    public constructor() {
    }
}

