"use strict";
/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.RoleCreateAttributes = void 0;
var ObjectSerializer_1 = require("./ObjectSerializer");
/**
* Attributes of the created role.
*/
var RoleCreateAttributes = /** @class */ (function () {
    function RoleCreateAttributes() {
    }
    RoleCreateAttributes.getAttributeTypeMap = function () {
        return RoleCreateAttributes.attributeTypeMap;
    };
    RoleCreateAttributes.deserialize = function (data) {
        var res = new RoleCreateAttributes();
        res.createdAt = ObjectSerializer_1.ObjectSerializer.deserialize(data.created_at, "Date", "date-time");
        res.modifiedAt = ObjectSerializer_1.ObjectSerializer.deserialize(data.modified_at, "Date", "date-time");
        if (data.name === undefined) {
            throw new TypeError("missing required attribute 'name' on 'RoleCreateAttributes' object");
        }
        res.name = ObjectSerializer_1.ObjectSerializer.deserialize(data.name, "string", "");
        return res;
    };
    RoleCreateAttributes.serialize = function (data) {
        var attributeTypes = RoleCreateAttributes.getAttributeTypeMap();
        var res = {};
        for (var _i = 0, _a = Object.entries(data); _i < _a.length; _i++) {
            var _b = _a[_i], key = _b[0], value = _b[1];
            if (!(key in attributeTypes)) {
                throw new TypeError(key + " attribute not in schema");
            }
        }
        res.created_at = ObjectSerializer_1.ObjectSerializer.serialize(data.createdAt, "Date", "date-time");
        res.modified_at = ObjectSerializer_1.ObjectSerializer.serialize(data.modifiedAt, "Date", "date-time");
        if (data.name === undefined) {
            throw new TypeError("missing required attribute 'name' on 'RoleCreateAttributes' object");
        }
        res.name = ObjectSerializer_1.ObjectSerializer.serialize(data.name, "string", "");
        return res;
    };
    RoleCreateAttributes.discriminator = undefined;
    RoleCreateAttributes.attributeTypeMap = {
        "createdAt": {
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        "modifiedAt": {
            "baseName": "modified_at",
            "type": "Date",
            "format": "date-time"
        },
        "name": {
            "baseName": "name",
            "type": "string",
            "format": ""
        }
    };
    return RoleCreateAttributes;
}());
exports.RoleCreateAttributes = RoleCreateAttributes;
//# sourceMappingURL=RoleCreateAttributes.js.map