/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RoleUpdateAttributes } from './RoleUpdateAttributes';
import { RolesType } from './RolesType';
import { HttpFile } from '../http/http';
import { AttributeTypeMap, UnparsedObject } from './ObjectSerializer';

/**
* Data related to the update of a role.
*/

export class RoleUpdateData {
    'attributes': RoleUpdateAttributes;
    /**
    * ID of the role.
    */
    'id': string;
    'type': RolesType;

    'unparsedObject'?:any;

    static readonly attributeTypeMap: AttributeTypeMap = {
        "attributes": {
            "baseName": "attributes",
            "type": "RoleUpdateAttributes",
            "required": true,
            
        },
        "id": {
            "baseName": "id",
            "type": "string",
            "required": true,
            
        },
        "type": {
            "baseName": "type",
            "type": "RolesType",
            "required": true,
            
        }    };

    static getAttributeTypeMap(): AttributeTypeMap {
        return RoleUpdateData.attributeTypeMap;
    }

    public constructor() {
    }
}



