"use strict";
/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.RolesResponse = void 0;
var ObjectSerializer_1 = require("./ObjectSerializer");
/**
* Response containing information about multiple roles.
*/
var RolesResponse = /** @class */ (function () {
    function RolesResponse() {
    }
    RolesResponse.getAttributeTypeMap = function () {
        return RolesResponse.attributeTypeMap;
    };
    RolesResponse.deserialize = function (data) {
        var res = new RolesResponse();
        res.data = ObjectSerializer_1.ObjectSerializer.deserialize(data.data, "Array<Role>", "");
        res.meta = ObjectSerializer_1.ObjectSerializer.deserialize(data.meta, "ResponseMetaAttributes", "");
        return res;
    };
    RolesResponse.serialize = function (data) {
        var attributeTypes = RolesResponse.getAttributeTypeMap();
        var res = {};
        for (var _i = 0, _a = Object.entries(data); _i < _a.length; _i++) {
            var _b = _a[_i], key = _b[0], value = _b[1];
            if (!(key in attributeTypes)) {
                throw new TypeError(key + " attribute not in schema");
            }
        }
        res.data = ObjectSerializer_1.ObjectSerializer.serialize(data.data, "Array<Role>", "");
        res.meta = ObjectSerializer_1.ObjectSerializer.serialize(data.meta, "ResponseMetaAttributes", "");
        return res;
    };
    RolesResponse.discriminator = undefined;
    RolesResponse.attributeTypeMap = {
        "data": {
            "baseName": "data",
            "type": "Array<Role>",
            "format": ""
        },
        "meta": {
            "baseName": "meta",
            "type": "ResponseMetaAttributes",
            "format": ""
        }
    };
    return RolesResponse;
}());
exports.RolesResponse = RolesResponse;
//# sourceMappingURL=RolesResponse.js.map