/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 */
import { RUMOperationJourneyCompositeRuleKind } from "./RUMOperationJourneyCompositeRuleKind";
import { RUMOperationJourneyPredicate } from "./RUMOperationJourneyPredicate";

import { AttributeTypeMap } from "../../datadog-api-client-common/util";

/**
 * A composite rule combining several predicates. Used as an alternative to `nodes` on a journey
 * step when several conditions must be matched together, in any order or in a specific order.
 */
export class RUMOperationJourneyCompositeRule {
  /**
   * The unique identifier of the composite rule. Generated by the server if omitted.
   */
  "compositeRuleId"?: string;
  /**
   * A hash of the composite rule's configuration, computed by the server.
   */
  "configVersion"?: string;
  /**
   * The rule used to combine the composite rule's predicates. `all_of` requires every predicate
   * to match, in any order. `in_order` requires every predicate to match in the given order.
   */
  "kind": RUMOperationJourneyCompositeRuleKind;
  /**
   * The maximum time window, in milliseconds, in which all predicates must match.
   */
  "maxWindowMs"?: number;
  /**
   * The list of predicates that must be matched by RUM events.
   */
  "predicates": Array<RUMOperationJourneyPredicate>;

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  "additionalProperties"?: { [key: string]: any };

  /**
   * @ignore
   */
  "_unparsed"?: boolean;

  /**
   * @ignore
   */
  static readonly attributeTypeMap: AttributeTypeMap = {
    compositeRuleId: {
      baseName: "composite_rule_id",
      type: "string",
    },
    configVersion: {
      baseName: "config_version",
      type: "string",
    },
    kind: {
      baseName: "kind",
      type: "RUMOperationJourneyCompositeRuleKind",
      required: true,
    },
    maxWindowMs: {
      baseName: "max_window_ms",
      type: "number",
      format: "int64",
    },
    predicates: {
      baseName: "predicates",
      type: "Array<RUMOperationJourneyPredicate>",
      required: true,
    },
    additionalProperties: {
      baseName: "additionalProperties",
      type: "{ [key: string]: any; }",
    },
  };

  /**
   * @ignore
   */
  static getAttributeTypeMap(): AttributeTypeMap {
    return RUMOperationJourneyCompositeRule.attributeTypeMap;
  }

  public constructor() {}
}
