/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SecurityFilter } from "./SecurityFilter";
import { SecurityFilterMeta } from "./SecurityFilterMeta";
import { AttributeTypeMap } from "./ObjectSerializer";

/**
 * All the available security filters objects.
 */

export class SecurityFiltersResponse {
  /**
   * A list of security filters objects.
   */
  "data"?: Array<SecurityFilter>;
  "meta"?: SecurityFilterMeta;

  "unparsedObject"?: any;

  static readonly attributeTypeMap: AttributeTypeMap = {
    data: {
      baseName: "data",
      type: "Array<SecurityFilter>",
    },
    meta: {
      baseName: "meta",
      type: "SecurityFilterMeta",
    },
  };

  static getAttributeTypeMap(): AttributeTypeMap {
    return SecurityFiltersResponse.attributeTypeMap;
  }

  public constructor() {}
}
