"use strict";
/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SecurityMonitoringSignalAttributes = void 0;
var ObjectSerializer_1 = require("./ObjectSerializer");
/**
* The object containing all signal attributes and their associated values.
*/
var SecurityMonitoringSignalAttributes = /** @class */ (function () {
    function SecurityMonitoringSignalAttributes() {
    }
    SecurityMonitoringSignalAttributes.getAttributeTypeMap = function () {
        return SecurityMonitoringSignalAttributes.attributeTypeMap;
    };
    SecurityMonitoringSignalAttributes.deserialize = function (data) {
        var res = new SecurityMonitoringSignalAttributes();
        res.attributes = ObjectSerializer_1.ObjectSerializer.deserialize(data.attributes, "{ [key: string]: Object; }", "");
        res.message = ObjectSerializer_1.ObjectSerializer.deserialize(data.message, "string", "");
        res.tags = ObjectSerializer_1.ObjectSerializer.deserialize(data.tags, "Array<Object>", "string");
        res.timestamp = ObjectSerializer_1.ObjectSerializer.deserialize(data.timestamp, "Date", "date-time");
        return res;
    };
    SecurityMonitoringSignalAttributes.serialize = function (data) {
        var attributeTypes = SecurityMonitoringSignalAttributes.getAttributeTypeMap();
        var res = {};
        for (var _i = 0, _a = Object.entries(data); _i < _a.length; _i++) {
            var _b = _a[_i], key = _b[0], value = _b[1];
            if (!(key in attributeTypes)) {
                throw new TypeError(key + " attribute not in schema");
            }
        }
        res.attributes = ObjectSerializer_1.ObjectSerializer.serialize(data.attributes, "{ [key: string]: Object; }", "");
        res.message = ObjectSerializer_1.ObjectSerializer.serialize(data.message, "string", "");
        res.tags = ObjectSerializer_1.ObjectSerializer.serialize(data.tags, "Array<Object>", "string");
        res.timestamp = ObjectSerializer_1.ObjectSerializer.serialize(data.timestamp, "Date", "date-time");
        return res;
    };
    SecurityMonitoringSignalAttributes.discriminator = undefined;
    SecurityMonitoringSignalAttributes.attributeTypeMap = {
        "attributes": {
            "baseName": "attributes",
            "type": "{ [key: string]: Object; }",
            "format": ""
        },
        "message": {
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        "tags": {
            "baseName": "tags",
            "type": "Array<Object>",
            "format": "string"
        },
        "timestamp": {
            "baseName": "timestamp",
            "type": "Date",
            "format": "date-time"
        }
    };
    return SecurityMonitoringSignalAttributes;
}());
exports.SecurityMonitoringSignalAttributes = SecurityMonitoringSignalAttributes;
//# sourceMappingURL=SecurityMonitoringSignalAttributes.js.map