"use strict";
/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SecurityFilterCreateData = void 0;
var ObjectSerializer_1 = require("./ObjectSerializer");
/**
* Object for a single security filter.
*/
var SecurityFilterCreateData = /** @class */ (function () {
    function SecurityFilterCreateData() {
    }
    SecurityFilterCreateData.getAttributeTypeMap = function () {
        return SecurityFilterCreateData.attributeTypeMap;
    };
    SecurityFilterCreateData.deserialize = function (data) {
        var res = new SecurityFilterCreateData();
        if (data.attributes === undefined) {
            throw new TypeError("missing required attribute 'attributes' on 'SecurityFilterCreateData' object");
        }
        res.attributes = ObjectSerializer_1.ObjectSerializer.deserialize(data.attributes, "SecurityFilterCreateAttributes", "");
        if (data.type === undefined) {
            throw new TypeError("missing required attribute 'type' on 'SecurityFilterCreateData' object");
        }
        if (['security_filters', undefined].includes(data.type)) {
            res.type = data.type;
        }
        else {
            throw TypeError("invalid enum value " + data.type + " for type");
        }
        return res;
    };
    SecurityFilterCreateData.serialize = function (data) {
        var attributeTypes = SecurityFilterCreateData.getAttributeTypeMap();
        var res = {};
        for (var _i = 0, _a = Object.entries(data); _i < _a.length; _i++) {
            var _b = _a[_i], key = _b[0], value = _b[1];
            if (!(key in attributeTypes)) {
                throw new TypeError(key + " attribute not in schema");
            }
        }
        if (data.attributes === undefined) {
            throw new TypeError("missing required attribute 'attributes' on 'SecurityFilterCreateData' object");
        }
        res.attributes = ObjectSerializer_1.ObjectSerializer.serialize(data.attributes, "SecurityFilterCreateAttributes", "");
        if (data.type === undefined) {
            throw new TypeError("missing required attribute 'type' on 'SecurityFilterCreateData' object");
        }
        if (['security_filters', undefined].includes(data.type)) {
            res.type = data.type;
        }
        else {
            throw TypeError("invalid enum value " + data.type + " for type");
        }
        return res;
    };
    SecurityFilterCreateData.discriminator = undefined;
    SecurityFilterCreateData.attributeTypeMap = {
        "attributes": {
            "baseName": "attributes",
            "type": "SecurityFilterCreateAttributes",
            "format": ""
        },
        "type": {
            "baseName": "type",
            "type": "SecurityFilterType",
            "format": ""
        }
    };
    return SecurityFilterCreateData;
}());
exports.SecurityFilterCreateData = SecurityFilterCreateData;
//# sourceMappingURL=SecurityFilterCreateData.js.map