/**
 * Datadog API V2 Collection
 * Collection of all Datadog Public endpoints.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@datadoghq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Once a signal is generated, the signal will remain “open” if a case is matched at least once within this keep alive window.
*/
export type SecurityMonitoringRuleKeepAlive = "0" | "60" | "300" | "600" | "900" | "1800" | "3600" | "7200" | "10800" | "21600" ;
