/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SecurityMonitoringRuleSeverity } from "./SecurityMonitoringRuleSeverity";
import { AttributeTypeMap } from "./ObjectSerializer";

/**
 * Options for third-party rules.
 */

export class SecurityMonitoringRuleThirdPartyOptions {
  /**
   * Notification targets for the root query.
   */
  "defaultNotifications"?: Array<string>;
  "defaultStatus"?: SecurityMonitoringRuleSeverity;
  /**
   * (Optional): the name of an attribute to override the first seen value of the third party signal.
   */
  "firstSeenOverride"?: string;
  /**
   * (Optional): the name of an attribute to override the last seen value of the third party signal.
   */
  "lastSeenOverride"?: string;
  /**
   * Root query of the rule.
   */
  "rootQuery"?: string;
  /**
   * Optional mapping of the third-party signal ID.
   */
  "signalId"?: string;

  "unparsedObject"?: any;

  static readonly attributeTypeMap: AttributeTypeMap = {
    defaultNotifications: {
      baseName: "defaultNotifications",
      type: "Array<string>",
    },
    defaultStatus: {
      baseName: "defaultStatus",
      type: "SecurityMonitoringRuleSeverity",
    },
    firstSeenOverride: {
      baseName: "firstSeenOverride",
      type: "string",
    },
    lastSeenOverride: {
      baseName: "lastSeenOverride",
      type: "string",
    },
    rootQuery: {
      baseName: "rootQuery",
      type: "string",
    },
    signalId: {
      baseName: "signalId",
      type: "string",
    },
  };

  static getAttributeTypeMap(): AttributeTypeMap {
    return SecurityMonitoringRuleThirdPartyOptions.attributeTypeMap;
  }

  public constructor() {}
}
