/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SecurityMonitoringSignalAttributes } from './SecurityMonitoringSignalAttributes';
import { SecurityMonitoringSignalType } from './SecurityMonitoringSignalType';
import { HttpFile } from '../http/http';
import { ObjectSerializer } from './ObjectSerializer';

/**
* Object description of a security signal.
*/

export class SecurityMonitoringSignal {
    'attributes'?: SecurityMonitoringSignalAttributes;
    /**
    * The unique ID of the security signal.
    */
    'id'?: string;
    'type'?: SecurityMonitoringSignalType;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: {[key: string]: {baseName: string, type: string, format: string}} = {
        "attributes": {
            "baseName": "attributes",
            "type": "SecurityMonitoringSignalAttributes",
            "format": ""
        },
        "id": {
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        "type": {
            "baseName": "type",
            "type": "SecurityMonitoringSignalType",
            "format": ""
        }    };

    static getAttributeTypeMap() {
        return SecurityMonitoringSignal.attributeTypeMap;
    }

    static deserialize(data: {[key: string]: any}): SecurityMonitoringSignal {
      let res = new SecurityMonitoringSignal();

      res.attributes = ObjectSerializer.deserialize(data.attributes, "SecurityMonitoringSignalAttributes", "")

      res.id = ObjectSerializer.deserialize(data.id, "string", "")

      if (['signal', undefined].includes(data.type)) {
          res.type = data.type;
      } else {
          throw TypeError(`invalid enum value ${ data.type } for type`);
      }


      return res;
    }

    static serialize(data: SecurityMonitoringSignal): {[key: string]: any} {
        let attributeTypes = SecurityMonitoringSignal.getAttributeTypeMap();
        let res: {[index: string]: any} = {};
        for (let [key, value] of Object.entries(data)) {
            if (!(key in attributeTypes)) {
                throw new TypeError(`${key} attribute not in schema`);
            }
        }
        res.attributes = ObjectSerializer.serialize(data.attributes, "SecurityMonitoringSignalAttributes", "")

        res.id = ObjectSerializer.serialize(data.id, "string", "")

        if (['signal', undefined].includes(data.type)) {
            res.type = data.type;
        } else {
            throw TypeError(`invalid enum value ${ data.type } for type`);
        }

        return res
    }
    
    public constructor() {
    }
}



