"use strict";
/**
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.UserInvitationData = void 0;
var ObjectSerializer_1 = require("./ObjectSerializer");
/**
* Object to create a user invitation.
*/
var UserInvitationData = /** @class */ (function () {
    function UserInvitationData() {
    }
    UserInvitationData.getAttributeTypeMap = function () {
        return UserInvitationData.attributeTypeMap;
    };
    UserInvitationData.deserialize = function (data) {
        var res = new UserInvitationData();
        if (data.relationships === undefined) {
            throw new TypeError("missing required attribute 'relationships' on 'UserInvitationData' object");
        }
        res.relationships = ObjectSerializer_1.ObjectSerializer.deserialize(data.relationships, "UserInvitationRelationships", "");
        if (data.type === undefined) {
            throw new TypeError("missing required attribute 'type' on 'UserInvitationData' object");
        }
        if (['user_invitations', undefined].includes(data.type)) {
            res.type = data.type;
        }
        else {
            throw TypeError("invalid enum value " + data.type + " for type");
        }
        return res;
    };
    UserInvitationData.serialize = function (data) {
        var attributeTypes = UserInvitationData.getAttributeTypeMap();
        var res = {};
        for (var _i = 0, _a = Object.entries(data); _i < _a.length; _i++) {
            var _b = _a[_i], key = _b[0], value = _b[1];
            if (!(key in attributeTypes)) {
                throw new TypeError(key + " attribute not in schema");
            }
        }
        if (data.relationships === undefined) {
            throw new TypeError("missing required attribute 'relationships' on 'UserInvitationData' object");
        }
        res.relationships = ObjectSerializer_1.ObjectSerializer.serialize(data.relationships, "UserInvitationRelationships", "");
        if (data.type === undefined) {
            throw new TypeError("missing required attribute 'type' on 'UserInvitationData' object");
        }
        if (['user_invitations', undefined].includes(data.type)) {
            res.type = data.type;
        }
        else {
            throw TypeError("invalid enum value " + data.type + " for type");
        }
        return res;
    };
    UserInvitationData.discriminator = undefined;
    UserInvitationData.attributeTypeMap = {
        "relationships": {
            "baseName": "relationships",
            "type": "UserInvitationRelationships",
            "format": ""
        },
        "type": {
            "baseName": "type",
            "type": "UserInvitationsType",
            "format": ""
        }
    };
    return UserInvitationData;
}());
exports.UserInvitationData = UserInvitationData;
//# sourceMappingURL=UserInvitationData.js.map