/**
 * Datadog API V2 Collection
 * Collection of all Datadog Public endpoints.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@datadoghq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Organization } from './Organization';
import { Permission } from './Permission';
import { Role } from './Role';
import { RoleAttributes } from './RoleAttributes';
import { RoleResponseRelationships } from './RoleResponseRelationships';
import { RolesType } from './RolesType';
import { HttpFile } from '../http/http';

/**
* An object related to a user.
*/
export class UserResponseIncludedItem {
    'attributes'?: RoleAttributes;
    /**
    * ID of the role.
    */
    'id'?: string;
    'type': RolesType;
    'relationships'?: RoleResponseRelationships;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "RoleAttributes",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "RolesType",
            "format": ""
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "RoleResponseRelationships",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UserResponseIncludedItem.attributeTypeMap;
    }
    
    public constructor() {
    }
}

