name: Send PR Approval Status

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches:
      - v2
    types: ["review_requested", "synchronize", "opened", "reopened"]
  pull_request_review:
    types:
      - submitted
      - dismissed

jobs:
  send_status:
    runs-on: ubuntu-latest
    if: >
      github.event.pull_request.draft == false &&
      !contains(github.event.pull_request.labels.*.name, 'ci/skip') &&
      !contains(github.event.pull_request.head.ref, 'datadog-api-spec/v2/test/') &&
      contains(github.event.pull_request.head.ref, 'datadog-api-spec/v2/generated')
    steps:
      - name: Get GitHub App token
        id: get_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.PIPELINE_GITHUB_APP_ID }}
          private-key: ${{ secrets.PIPELINE_GITHUB_APP_PRIVATE_KEY }}
          repositories: datadog-api-spec
      - name: Get pull request number
        id: get_pr_number
        run: |
          spec_pr=$(echo "${{ github.event.pull_request.head.ref }}" | sed 's/.*generated\/\([0-9]*\).*/\1/')
          echo "spec_pr=${spec_pr}" >> $GITHUB_OUTPUT
      - name: Post PR review status check
        uses: DataDog/github-actions/post-review-status@65b4875f33ad773d7ba4b005a2cb5f35020295f3
        with:
          github-token: ${{ steps.get_token.outputs.token }}
          repo: datadog-api-spec
          context: datadog-api-client-typescript/v2
          pull-request: ${{ steps.get_pr_number.outputs.spec_pr }}
