name: Publish package on NPM

permissions:
  contents: write

on:
  release:
    types:
      - prereleased
      - released
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Releasing tag ${{ github.event.release.tag_name }}
        run: |
          corepack enable; yarn set version 4.9.1

          # Get tag name from event
          tag_name="${{ github.event.release.tag_name }}"

          if [[ ! "$tag_name" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            cd $(echo $tag_name | rev | cut -d'/' -f2- | rev)
          fi

          cmd="yarn npm publish --access public"
          if [ "${{ github.event.release.prerelease }}" == "true" ]; then
            cmd+=" --tag=beta"
          else
            cmd+=" --tag=latest"
          fi

          eval $cmd
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.YARN_NPM_AUTH_TOKEN }}
          COREPACK_ENABLE_DOWNLOAD_PROMPT: 0
