name: Reusable Examples Workflow

on:
  workflow_call:
    inputs:
      target-branch:
        description: 'Branch to checkout and test (defaults to the calling branch)'
        required: false
        type: string
        default: ''
      examples-script:
        description: 'Examples script to execute'
        required: false
        type: string
        default: './check-examples.sh'
      node-version:
        description: 'Node.js version to use for examples'
        required: false
        type: string
        default: '16'

jobs:
  examples:
    runs-on: ubuntu-latest
    if: (github.event.pull_request.draft == false && !contains(github.event.pull_request.labels.*.name, 'ci/skip') && !contains(github.event.pull_request.head.ref, 'datadog-api-spec/test/')) || github.event_name == 'schedule'
    steps:
      - uses: actions/checkout@v3
        with:
          repository: DataDog/datadog-api-client-typescript
          ref: ${{ inputs.target-branch || github.ref }}
      - name: Enable Corepack
        run: corepack enable
        env:
          COREPACK_ENABLE_DOWNLOAD_PROMPT: 0
      - name: Set up Node ${{ inputs.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'yarn'
      - name: Check examples
        run: ${{ inputs.examples-script }}
        shell: bash