name: Run Integration Tests

on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 4 * * *"

concurrency:
  group: integration-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    if: >
      (github.event_name == 'pull_request' &&
      github.event.pull_request.draft == false &&
      !contains(github.event.pull_request.labels.*.name, 'ci/skip') &&
      !contains(github.event.pull_request.head.ref, 'datadog-api-spec/test/') &&
      contains(github.event.pull_request.labels.*.name, 'ci/integrations')) ||
      github.event_name == 'schedule'
    services:
      datadog-agent:
        image: datadog/agent:latest
        ports:
          - 8126:8126
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
          DD_HOSTNAME: "none"
          DD_INSIDE_CI: "true"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node 14
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Run integration tests
      run: ./run-tests.sh
      shell: bash
      env:
        CI: "true"
        DD_AGENT_HOST: localhost
        DD_ENV: prod
        DD_SERVICE: datadog-api-client-typescript
        DD_TAGS: "team:integration-tools-and-libraries"
        DD_TEST_CLIENT_API_KEY: ${{ secrets.DD_CLIENT_API_KEY }}
        DD_TEST_CLIENT_APP_KEY: ${{ secrets.DD_CLIENT_APP_KEY }}
        DD_TRACE_ANALYTICS_ENABLED: "true"
        RECORD: "none"
