name: Run Integration Tests

permissions:
  contents: read

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
      - labeled
      - unlabeled
    branches:
      - master
  schedule:
    - cron: "0 4 * * *"

concurrency:
  group: integration-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test_integration:
    runs-on: ubuntu-latest
    if: >
      (github.event_name == 'pull_request' &&
      github.event.pull_request.draft == false &&
      !contains(github.event.pull_request.labels.*.name, 'ci/skip') &&
      !contains(github.event.pull_request.head.ref, 'datadog-api-spec/test/') &&
      contains(github.event.pull_request.labels.*.name, 'ci/integrations')) ||
      github.event_name == 'schedule'
    services:
      datadog-agent:
        image: gcr.io/datadoghq/agent:latest
        ports:
          - 8126:8126
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
          DD_HOSTNAME: "none"
          DD_INSIDE_CI: "true"
    steps:
      - name: Get GitHub App token
        if: github.event_name == 'pull_request'
        id: get_token
        uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # v1.12.0
        with:
          app-id: ${{ secrets.PIPELINE_GITHUB_APP_ID }}
          private-key: ${{ secrets.PIPELINE_GITHUB_APP_PRIVATE_KEY }}
          repositories: datadog-api-spec
      - name: Checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Post pending status check
        if: github.event_name == 'pull_request' && contains(github.event.pull_request.head.ref, 'datadog-api-spec/generated/')
        uses: DataDog/github-actions/post-status-check@65b4875f33ad773d7ba4b005a2cb5f35020295f3 # v2.3.0
        with:
          github-token: ${{ steps.get_token.outputs.token }}
          repo: datadog-api-spec
          status: pending
          context: integration
      - name: Set up Node 16
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: 16
          cache: 'yarn'
      - name: Run integration tests
        run: ./run-tests.sh
        shell: bash
        env:
          CI: "true"
          DD_AGENT_HOST: localhost
          DD_ENV: prod
          DD_SERVICE: datadog-api-client-typescript
          DD_TAGS: "team:integrations-tools-and-libraries"
          DD_TRACE_PROPAGATION_STYLE_INJECT: "datadog"
          DD_TEST_CLIENT_API_KEY: ${{ secrets.DD_CLIENT_API_KEY }}
          DD_TEST_CLIENT_APP_KEY: ${{ secrets.DD_CLIENT_APP_KEY }}
          RECORD: "none"
          SLEEP_AFTER_REQUEST: "${{ vars.SLEEP_AFTER_REQUEST }}"
      - name: Post failure status check
        if: failure() && github.event_name == 'pull_request' && contains(github.event.pull_request.head.ref, 'datadog-api-spec/generated/')
        uses: DataDog/github-actions/post-status-check@65b4875f33ad773d7ba4b005a2cb5f35020295f3 # v2.3.0
        with:
          github-token: ${{ steps.get_token.outputs.token }}
          repo: datadog-api-spec
          status: failure
          context: integration
      - name: Post success status check
        if: "!failure() && github.event_name == 'pull_request' && contains(github.event.pull_request.head.ref, 'datadog-api-spec/generated/')"
        uses: DataDog/github-actions/post-status-check@65b4875f33ad773d7ba4b005a2cb5f35020295f3 # v2.3.0
        with:
          github-token: ${{ steps.get_token.outputs.token }}
          repo: datadog-api-spec
          status: success
          context: integration
